QWidget {
	background-color: rgb(_background_color_);
	color:rgb(_text_color_);
	border-style:solid;
	border-color: rgba(85, 170, 255,100);
}

#node_widget_button_frame{
	border-radius: 15px;
	color:gray;
}

#pm_stage_item_state_pushButton, #pm_stage_item_user_pushButton{
	border-radius: 17px;
}

#shot_crea_main_frame{
	border-radius:20px;
	border-bottom-left-radius:0px;
	border: 1px solid gray;
}

#update_widget_frame, #update_title_frame{
	background-color:rgb(_top_level_widget_color_);
}

#ref_list_asset_frame{
	border-radius:10px;
}

#update_title_label, #update_text_label{
	color:white;
}

#update_web_pushButton, #update_doc_pushButton{
	background:transparent;
	color:gray;
}

#file_viewer_main_frame{
	background-color:rgb(_background_color_)
}

#update_web_pushButton:hover, #update_doc_pushButton:hover{
	color:white;
}

#only_openned_tickets_pushButton{
	border-radius:0px;
	border-bottom-left-radius:14px;
	border-top-left-radius:14px;
}

#ticket_adressed_to_me_pushButton{
	border-radius:0px;
	border-bottom-right-radius:14px;
	border-top-right-radius:14px;
}

#ticket_main_frame{
	background-color:rgba(_middle_level_widget_color_, 200)
}

#ticket_header_frame{
	background-color:rgba(_middle_level_widget_color_, 220)
}

#tickets_scrollArea, #scrollAreaWidgetContents_3{
	background-color:transparent;
}

#ticket_user_label, #tiret_label, #ticket_date_label, #ticket_state_label, #close_date_label, #ticket_comment_label{
	color:gray;
}

#update_scrollArea{
	background-color:transparent;
}

#update_title_label{
	font: bold;
}

#file_viewer_plainTextEdit{
	background-color:rgb(_top_level_widget_color_);
}

#file_viewer_menubar{
	background-color:rgb(_top_level_widget_color_);
}

#wsd_proxy_pushButton, #wsd_visible_pushButton{
	border-radius:0px;
	border-top-left-radius:20px;
	border-bottom-left-radius:20px;
	border-right: none;
}

#playblasts_listWidget{
	background-color:transparent;
}

#subprocess_percent_progressBar::chunk{
	background-color:#FF9966;
}

#pb_ma_scrollArea{
	background-color:transparent;
}

#wsd_hidden_pushButton, #wsd_asset_pushButton{
	border-radius:0px;
	border-top-right-radius:20px;
	border-bottom-right-radius:20px;
	border-left: none;
}

#stats_main_frame{
	border-radius:15px;
}

#imported_asset_m_wsd_frame{
	border: 1px solid gray;
	border-radius: 3px;
}

#loading_ui_horizontalFrame{
	background-color:rgb(_top_level_widget_color_);
}

#text_loading_frame{
	background-color:rgba(_middle_level_widget_color_, 100);
}

#chat_file_frame{
	background-color:rgb(_very_lower_level_widget_color_);
}

#export_ma_assets_listWidget{
	border: 1px solid gray;
}

#chat_frame{
	background-color:rgb(_middle_level_widget_color_);
}

#messages_frame{
	background-color:rgb(_low_level_widget_color_);
}

#design_work_progressBar::chunk, #geo_work_progressBar::chunk, #rig_work_progressBar::chunk, #hair_work_progressBar::chunk, #texturing_work_progressBar::chunk, #shading_work_progressBar::chunk{
	background-color:#cfafe3;
	border-radius:6px;
}


#design_stats_progressBar::chunk, #geo_stats_progressBar::chunk, #rig_stats_progressBar::chunk, #hair_stats_progressBar::chunk, #texturing_stats_progressBar::chunk, #shading_stats_progressBar::chunk{
	background-color:#cfafe3;
	border-radius:6px;
}

#design_work_progressBar, #geo_work_progressBar, #rig_work_progressBar, #hair_work_progressBar, #texturing_work_progressBar, #shading_work_progressBar{
	border-radius:6px;
}
#design_stats_progressBar, #geo_stats_progressBar, #rig_stats_progressBar, #hair_stats_progressBar, #texturing_stats_progressBar, #shading_stats_progressBar{
	border-radius:6px;
}


#message_widget_image_label{
	background-color:transparent;
}

#message_user_label{
	color:gray;
}

#message_main_frame{
	background-color:rgb(_top_level_widget_color_);
}

#chat_top_horizontalFrame{
	border-radius:20px;
	border-bottom-left-radius:0px;
	border-bottom-right-radius:0px;
}

#message_widget_image_layout, #message_widget_spacer_frame{
	background-color:transparent;
}

#message_widget_image_layout, #message_widget_spacer_frame{
	margin:0px;
	padding:0px;
}

#running_main_frame{
	border-radius: 5px;
	border-bottom-right-radius:0px;
}

#running_scrollArea, #chat_main_scrollArea, #chat_main_lineEdit, #chat_scrollAreaWidgetContents{
	background-color:transparent;
}

#message_main_frame{
	border-radius:25px;
}

#chat_file_pushButton{
	padding-left:16px;
	padding-right:16px;
	border-radius: 20px;
}

#added_chat_file_pushButton{
	padding-left:16px;
	padding-right:16px;
	border-radius: 20px;
}

#chat_show_more_pushButton{
	border-radius:20px;
}

#chat_file_frame{
	border-bottom:1px solid gray;
}

#server_user_image_label{
	background-color:transparent;
}

#running_item_main_frame{
	background-color:rgba(_top_level_widget_color_, 150);
	border-radius:10px;
}

#server__users_verticalFrame{
	background-color:rgba(_middle_level_widget_color_, 100);
}

#welcome_version_label{
	color:gray;
}

#server_users_frame{
	border-radius:19px;
}

#welcome_stacked_widget_frame{
	background-color:rgba(_top_level_widget_color_, 180);
	border-radius:20px;
}

#welcome_info_title_frame{
	background-color:transparent;
}

#close_pushButton{
	border-radius:13px;
}

#welcome_main_textEdit{
	background-color:transparent;
}

#welcome_right_pushButton{
	border-radius:0px;
	border-top-right-radius:20px;
	border-bottom-right-radius:20px;
}

#welcome_left_pushButton{
	border-radius:0px;
	border-top-left-radius:20px;
	border-bottom-left-radius:20px;
}

#manual_export_main_frame{
	background-color:transparent;
}

#references_number_label, #selection_label, #scene_manager_label, #reference_list_label, #exports_manager_label{
	color:gray;
}

#reference_list_listWidget, #icons_list_listWidget{
	background-color:transparent;
}

#reference_list_listWidget::item{
	padding:0px;
	border-radius:3px;	
	background-color: rgba(_middle_level_widget_color_, 110);
	color: rgb(_text_color_);
}

#icons_list_listWidget::item{
	padding:3px;
	border-radius:3px;	
	background-color: rgba(_middle_level_widget_color_, 110);
	color: rgb(_text_color_);
}

#reference_list_listWidget::item:hover, #icons_list_listWidget::item:hover {
	padding:0px;
	background-color: rgba(_top_level_widget_color_, 120);
}

#reference_list_listWidget::item:selected, #icons_list_listWidget::item:selected {
	padding:0px;
	background-color: rgba(_top_level_widget_color_, 120);
	color: rgb(_text_color_);
	border: 1px solid gray;
}

#reference_list_item_frame{
	background-color:transparent;
}

#export_manager_drop_lineEdit{
	background-color:transparent;
}


#manual_export_plainTextEdit{
	background-color:transparent;
}

#manual_export_listView{
	background-image:url(ressources/images/drop.png) 0 0 0 0;
	background-repeat: none;
	background-position: center;
}

#manual_export_main_frame_2{
	background-color:transparent;
}

#Infos_frame{
	background-color:rgb(_middle_level_widget_color_);
	border-radius:0px;
}

#comment_dialog_plainTextEdit{
	background-color:rgb(_low_level_widget_color_);
}



#export_asset_widget_pushButton{
	border-radius:14px;
}

#export_asset_widget_number_label{
	color : gray;
}

#export_widget_frame{
	background-color:rgb(_very_lower_level_widget_color_);
	border-radius:23px;
	border : 1px solid gray;
}

#show_more_pushButton, #show_less_pushButton{
	border-radius:14px;
}

#exports_number_label{
	color:gray;
}

#manual_publish_horizontalFrame, #ticket_toolbar_frame{
	background-color:transparent;
	padding:0px;
	margin:0px;
}

#manual_publish_pushButton, #batch_publish_pushButton, #add_empty_file_pushButton, #batch_playblast_pushButton, #open_ticket_pushButton{
	border-radius:24px;
}

#about_author_label{
	color:gray;
}

#running_close_pushButton{
	border-radius:13px;
}

#show_more_horizontalFrame{
	background-color:transparent;
	margin:0px;
	padding:0px;
}

#list_export_widget_frame, #list_playblast_widget_frame, #list_version_widget_frame{
	background-color:transparent;
	border-radius:2px;
}

#list_export_widget_frame:hover, #list_playblast_widget_frame:hover, #list_version_widget_frame:hover{
	
}

#list_verticalFrame{
	background-color:transparent;
	border-radius:0px;
}

#playblast_number_label, #versions_number_label{
	color:gray;
}

#export_widget_folder_pushButton, #export_widget_tx_pushButton, #export_widget_tex_pushButton, #playblast_widget_comment_pushButton, #version_open_software_pushButton, #version_widget_comment_pushButton, #playblast_widget_folder_pushButton, #export_widget_comment_pushButton, #playblast_widget_view_pushButton, #version_widget_delete_pushButton{
	background-color:transparent;
	border-radius:0px;
}

#exports_manager_header_Frame{
	background-color:transparent;
}

#export_widget_folder_pushButton:hover, #export_widget_tx_pushButton:hover, #export_widget_tex_pushButton:hover, #version_open_software_pushButton:hover, #playblast_widget_comment_pushButton:hover, #version_widget_comment_pushButton:hover, #playblast_widget_folder_pushButton:hover, #export_widget_comment_pushButton:hover, #playblast_widget_view_pushButton:hover, #version_widget_delete_pushButton:hover{
	background-color:rgb(_top_level_widget_color_)
}

#export_widget_asset_label, #export_widget_user_label, #export_widget_date_label, #export_widget_comment_label, #export_widget_version_label{
	color:white;
}

#sanity_exports_pushButton:checked, #show_all_exports_pushButton:checked{
	background-color: rgba(_very_lower_level_widget_color_, 100);
}

#sanity_exports_pushButton{
	border-radius:14px;
	border-top-right-radius:0px;
	border-bottom-right-radius:0px;
}

#show_all_exports_pushButton{
	border-radius:14px;
	border-top-left-radius:0px;
	border-bottom-left-radius:0px;
}

QToolBox::tab {
    background: rgb(_very_lower_level_widget_color_);
    border-radius: 5px;
    color: gray;
}

QToolBox::tab:selected { /* italicize selected tabs */
    color: white;
    font:bold;
}

#state_label{
	font:bold;
}

#node_editor_frame{
	background-color:rgb(_low_level_widget_color_);
	border: 2px solid rgb(_low_level_widget_color_);
}

#reference_list_frame{
	background-color:rgb(_low_level_widget_color_);
	border: 2px solid rgb(_low_level_widget_color_);
}

#wall_environment_label_2{
	color:gray;
}

#exports_main_frame, #versions_manager_main_frame{
	background-color:rgb(_low_level_widget_color_);
}

#version_main_listView, #scrollAreaWidgetContents, #versions_manager_main_scrollArea{
	background-color:transparent;
}

#versions_manager_label{
	color:gray;
}

#project_widget_frame{
	background-color:rgb(_very_lower_level_widget_color_);
}

#exports_list_scrollArea{
	background-color:transparent;
}

#project_widget_frame:hover{
	border:1px solid gray;
}


#creation_filter_pushButton:checked{
	border : 1px solid #93d1ff;
}

#new_filter_pushButton:checked{
	background-color: #b6e3a0;
}

#delete_asset_pushButton, #quit_popup_quit_pushButton{
	background-color:#ff8383;
}

#delete_asset_pushButton:hover, #quit_popup_quit_pushButton:hover{
	background-color:#ff9292;
}

#delete_asset_pushButton:pressed, #quit_popup_quit_pushButton:pressed{
	background-color:#913e3e;
}

#publish_filter_pushButton:checked{
	border : 1px solid #a4ff83;
}

#remove_filter_pushButton:checked{
	border : 1px solid #ff8383;
}

#current_asset_label{
	background-color:rgba(_background_color_, 90);
	padding-left:10px;
}

#popup_message_label{
	color:gray;
}

#level_label_number{
	font: 63 10pt "Bahnschrift SemiBold SemiConden";
	color : gray
}

#user_image_label{
	border-radius:30px;
}

#password_project_formFrame{
	border-top-right-radius:10px;
	border-top-left-radius:10px;
}

#settings_project_frame{
	border-bottom-right-radius:10px;
	border-bottom-left-radius:10px;
}

#imported_version_label, #imported_namespace_label, #imported_asset_label, #imported_variant_label, #imported_scene_label, #file_name_label, #imported_user_name_label, #imported_date_label, #imported_comment_label, #imported_software_label, #promotion_label, #project__name_name_label, #path_name_label, #ram_name_label, #cpu_name_label{
	color:gray;
}


#imported_asset_update_pushButton{
	padding:5px;
}


#chart_textEdit{
	background-color:transparent;
	color: gray;
}

#jokes_textEdit{
	background-color:transparent;
}

#options_pushButton{
	border-radius:0px;
	padding:7px;
	padding-left:12px;
	padding-right:12px;
	Text-align:left;
	background-color:rgb(_low_level_widget_color_)
}

#options_pushButton:hover{
	background-color:rgba(255,255,255,80)
}

#options_frame{
	border-radius:10px;
	border-bottom-left-radius:0px;
}

#trash_pushButton{
	background-color:transparent;
	border-image: url(ressources/images/trash.png) 0 0 0 0 stretch stretch;
}

#trash_pushButton:hover{
	border-image: url(ressources/images/trash_hover.png) 0 0 0 0 stretch stretch;
}

#update_all_pushButton{
	background-color:transparent;
	border-image: url(ressources/images/update.png) 0 0 0 0 stretch stretch;
}

#update_all_pushButton:hover{
	border-image: url(ressources/images/update_hover.png) 0 0 0 0 stretch stretch;
}


#node_editor_scrollArea{
	background-color: transparent;
}

#header_frame{
	background-color: rgb(_middle_level_widget_color_);
}

#chat_server_frame{
	border-radius:6px;
	background-color: rgba(_middle_level_widget_color_, 240);
}

#loading_frame{
	background-color: transparent;
	margin:0px;
	padding: 0px;
}

#wizard_version_label, #loading_label{
	color:gray;
}

#loading_progressBar::chunk{
	background-color: #7785de;
	margin:0px;
	padding:0px;
	border-radius: 0px;
}

#loading_progressBar{
	background-color: #454c7b;
	border-radius: Opx;
	margin:0px;
	padding:0px;
}

#file_viewer_textEdit{
	background-image: url(ressources/images/drop.png) 0 0 0 0 stretch stretch;
	background-repeat: none;
	background-position: center;
	border : 2px solid white;
}

#user_widget_frame{
	background-color:transparent;
	padding:0px;
	margin:0px;
}

#wizard_desktop_transparent_frame, #show_wizard_pushButton{
	padding:0px;
	margin:0px;
	border-bottom-left-radius:30px;
	border-bottom-right-radius:30px;
}

#asset_variant_label{
	color:gray;
}

#stats_frame{
	background-color : rgb(_top_level_widget_color_);
	margin:0px;
}

#tab_widget_layout{
	margin:5px;
}

#game_stats_frame{
	background-color : rgb(_top_level_widget_color_);
	margin:0px;
}

#shop_pushButton, #stuff_pushButton, #cup_pushButton{
	border-radius : 0px;
	margin:0px;
	padding:0px;
}

#shop_pushButton:pressed, #stuff_pushButton:pressed, #cup_pushButton:pressed{
	background-color: rgb(_background_color_);
}

#shop_pushButton{
	border-top-right-radius:10px;
}

#stuff_pushButton{
	border-bottom-right-radius:10px;
}

#message_textEdit{
	background-color : rgb(_background_color_);
}

#user_frame{
	background-color : rgb(_top_level_widget_color_);
	margin:0px;
	border-top-right-radius:0px;
	border-bottom-right-radius:0px;
}

#header{
	background-color: rgb(_background_color_);
	border-radius:0px;
	margin:0px;
	padding:0px;
}

#wall_event_frame{
	background-color: rgba(_top_level_widget_color_, 200);
	margin : 0px;
	border-radius:10px;
	border-top-right-radius:0px;
	border-top-left-radius:0px;
}

#wall_event_top_frame{
	margin : 0px;
	border-radius:10px;
	border-bottom-right-radius:0px;
	border-bottom-left-radius:0px;
}

#color_id_frame{
	border-radius:5px;
}

#wall_event_frame:hover{
	background-color: rgb(_top_level_widget_color_);
}

#date_widget_frame, #seen_widget_frame{
	background-color: rgb(_very_lower_level_widget_color_)
}

#seen_widget_frame{
	border-bottom: 1px solid #b3d075;
}

#message_date_label{
	color: Gray;
}

#wall_event_user_label{
	font: 90 10pt "MS Shell Dlg 2";
}

#wall_event_message_label{
	color:Gray;
}

#wall_event_top_line_frame, #wall_event_bottom_line_frame{
	background-color:gray;
	border-radius :0px;
	padding:0px;
	margin:0px;
	margin-left:4px;
	margin-right:4px;
}

#wall_event_point_frame{
	background-color:transparent;
	border-radius: 6px;
	border : 4px solid gray;
}



#wall_event_date_label{
	color:rgba(_text_color_,100);
}

#popup_background_frame{
	background-color : rgb(_top_level_widget_color_);
	padding : 0px;
	margin : 0px;
	border-radius: 15px;
}

#save_popup_frame{
	background-color : rgba(_background_color_, 205);
	border-radius : 38px;
	padding : 0px;
	margin : 0px;
}

#popup_close_pushButton{
	border-radius : 14px;
}

#popup_image_frame, #popup_data_frame{
	background-color:transparent;
}

#wall_event_icon_frame{
	background-color:transparent;
}

#wizard_icon{
	background-color : transparent;
	border-image: url(ressources/images/wizard_icon.png) 0 0 0 0 stretch stretch;
	margin:0px;
	padding:0px;
}

#wizard_pushButton{
	background-color : transparent;
}

#add_variant_pushButton{
	image: url(ressources/images/add.png);
	border-radius : 0px;
	background-color : rgba(_low_level_widget_color_,120);
}

#add_variant_pushButton:hover{
	background-color: rgba(_hover_widget_color_, 160);
}

#log_textEdit, #log_py_plainTextEdit, #log_lines_plainTextEdit{
	background-color: rgb(_very_lower_level_widget_color_);
	color:rgb(_text_color_);
	padding : 5px;
}

#log_textEdit{
	color:rgba(_text_color_, 150);
}

#log_lines_plainTextEdit{
	background-color: rgba(_background_color_, 80);
	border-right : 1px solid gray;
	padding-right:0px;
	padding-left:10px;
}

#wall_event_icon_frame{
	padding:0px;
	margin:0px;
}

#tab_widget_layout{
	background-color:transparent;
	padding : 0px;
	margin : 0px;
}

#avatar_pushButton{
	border-radius:75px;
	margin:0px;
}

#user_image_pushButton{
	border-radius:35px;
	margin:0px;
	border : 4px solid rgb(_hover_widget_color_);
}

#user_image_pushButton:hover{
	border : 4px solid gray;
}

#user_image_pushButton:pressed {
	border : 4px solid rgb(_pressed_widget_color_);
}

#user_bg_frame{
	padding:0px;
	margin:0px;
	background-color:transparent;
}

#publish_state_frame{
	border-radius:5px;
}

#stuff_name_label{
	font: 90 14pt "8514oem";
	font-size:100px;
}

#shop_stuff_Frame{
	background-color:rgb(_middle_level_widget_color_);
	border-radius:0px;
	border : 2px solid white;
}

#stuff_line, #stuff_line_2{
	background-color:White;
}

#buy_pushButton{
	background-color:transparent;
	border-image:url(ressources/images/buy.png) 0 0 0 0 stretch stretch;
}

#buy_pushButton:pressed{
	background-color:transparent;
	border-image:url(ressources/images/buy_pressed.png) 0 0 0 0 stretch stretch;
}

#classment_label{
	background-color: rgba(_background_color_, 100);
	padding:3px;
	border-radius:20px;
}

#env_textEdit, #additionnal_textEdit, #executable_lineEdit{
	background-color: rgb(_background_color_);
}

#shop_header_frame{
	background-color: rgba(_background_color_, 100);
	padding :0px;
	margin : 0px;
}

#log_icon, #log_lineEdit{
	background-color : transparent;
}

#log_lineEdit{
	padding-left : 1px;
}

#new_user_warning_label{
	color:grey;
}

#wall_main_frame{
	background-color:transparent;
}

#log_frame{
	background-color : rgb(_background_color_);
	margin : 0px;
	font:9pt;
}

#diamond_frame{
	border-image: url(ressources/images/diamond.png) 0 0 0 0 stretch stretch;
}

#gold_frame{
	border-image: url(ressources/images/gold.png) 0 0 0 0 stretch stretch;
}

#avatar_frame{
	background-color: rgb(_middle_level_widget_color_);
	border : 1px solid rgb(_background_color_);
	border-radius: 3px;
}

#node_editor_buttons_frame, #references_number_frame, #selection_frame{
	border-radius:10px;
	background-color:rgba(_middle_level_widget_color_,100);
}

#main_frame{
	background-color:transparent;
}

#image_button{
	background-color:transparent;
	border-radius: 0px;
	padding:0px;
	margin:Opx;
}


#jokes_main_verticalFrame{
	background-color:transparent;
}

#star1_pushButton, #star2_pushButton, #star3_pushButton, #star4_pushButton, #star5_pushButton{
	background-color:transparent;
}

#star1_pushButton:hover, #star2_pushButton:hover, #star3_pushButton:hover, #star4_pushButton:hover, #star5_pushButton:hover{
	border-image: url(ressources/images/star_hover.png) 0 0 0 0 stretch stretch;
}

#jokes_widget_horizontalFrame{
	background-color:rgb(_top_level_widget_color_);
}

#votes_frame{
	background-color:transparent;
}

#float_note_label{
	color:gray;
}

#previous_joke_pushButton{
	border-radius:0px;
	border-top-right-radius:0px;
	border-bottom-right-radius:0px;
}

#add_joke_pushButton, #user_jokes_pushButton, #stats_pushButton, #user_tickets_pushButton{
	border-radius:14px;
	border : 1px solid gray;
}


#next_joke_pushButton{
	border-radius:0px;
	border-top-left-radius:0px;
	border-bottom-left-radius:0px;
}

#publish_last_pushButton:icon{
	image: url(ressources/images/tree_arrow_down.png);
}

#search_frame{
	image: url(ressources/images/search.png);
	background-color: transparent;
}

#search_lineEdit{
	background-color: transparent;
}

#search_horizontalFrame{
	background-color: rgb(_top_level_widget_color_);
	border-radius:3px;
}

#message_frame_left{
	background-color:rgba(255, 255, 255, 90);
	border-radius:14px;
}

#message_frame_right{
	background-color: rgb(_top_level_widget_color_);
	border-radius:14px;
}

#message_user_label{
	color:rgba(_text_color_, 120);
}

#message_textEdit{
	background-color:transparent;
}

#message_text_label{
	color:white;
}

#chat_scrollArea, #scrollAreaWidgetContents{
	background-color : transparent;
}

#chat_content_frame{
	border-radius:23px;
	background-color : rgb(_top_level_widget_color_);
}

#wall_scrollArea{
	background-color : rgba(_background_color_, 120);
}

#wall_scrollArea_widget{
	background-color:transparent;
}

#wall_event_main_frame{
	background-color:transparent;
}

#send_message_lineEdit{
	background-color: transparent;
}

#infos_scrollArea, #info_widgetContent {
	background-color: transparent;
}

#info_frame, #info_frame_2{
	background-color:rgba(_background_color_, 20);
}

#launch_pushButton{
	background-color:transparent;
} 

#launch_pushButton_Frame{
	background-color: rgb(_top_level_widget_color_);
	margin:0px;
	padding:0px;
}

#launch_pushButton_Frame:hover{
	background-color: rgb(_hover_widget_color_);
}


#asset_comment_textEdit{
	background-color: transparent;
}

#comment_frame{
	background-color : rgba(_low_level_widget_color_, 160);
	padding-left:9px;
	padding-right:9px;
	padding-top:9px;
	padding-bottom:9px;
	margin:0px;
}

#comment_pushButton{
	border-image: url(ressources/images/comment.png) 0 0 0 0 stretch stretch;
	background-color:transparent;
}

#variants_comboBox, #software_comboBox, #versions_comboBox{
	background-color:rgba(_low_level_widget_color_, 160);
	border-radius:0px;
	padding-left:10px;
}

#variants_comboBox:hover, #software_comboBox:hover, #versions_comboBox:hover{
	background-color: rgba(_hover_widget_color_, 160);
}

#variants_comboBox::drop-down{
	border-radius:0px;
	background-color:transparent;
}

#versions_comboBox::drop-down{
	border-radius:0px;
	background-color:transparent;
}

#software_comboBox::drop-down{
	border-radius:0px;
	background-color:transparent;
}


#comment_pushButton:hover{
	border-image: url(ressources/images/comment_hover.png) 0 0 0 0 stretch stretch;
}

#comment_pushButton:pressed{
	border-image: url(ressources/images/comment_clicked.png) 0 0 0 0 stretch stretch;
}


#send_message_frame{
	background-color: rgba(_background_color_, 120);
	margin:0px;
	padding:0px;
}

QLabel{
	background-color:transparent;
	padding-bottom:3px;
}

QTreeView {
	font:14px;
    show-decoration-selected: 0;
	background-color: rgb(_middle_level_widget_color_);
	padding-left:0px;
	padding-top:0px;
	padding-right:0px;
}

QTreeView::item {
	padding:3px;
	border-radius:0px;	
	background-color: rgba(_middle_level_widget_color_, 110);
	color: rgb(_text_color_);
}

QTreeView::item:hover {
	padding:3px;
	background-color: rgb(_top_level_widget_color_);
	border-radius:0px;	
}

QTreeView::item:selected {
	padding:3px;
	background-color: rgb(_top_level_widget_color_);
	color: rgb(_text_color_);
	border: 1px solid #7785de;
}

QTreeView::item:selected:active{
	border: 1px solid #7785de;
}

QTreeView::branch{
	background-color:transparent;
}

QTreeView::branch:has-children:!has-siblings:closed,
QTreeView::branch:closed:has-children:has-siblings {
        image: url(ressources/images/folder_closed.png);
        background-color:rgba(_low_level_widget_color_, 110)
}

QTreeView::item:has-children{
	background-color: rgba(_low_level_widget_color_, 100);
}

QTreeView::branch:open:has-children:!has-siblings,
QTreeView::branch:open:has-children:has-siblings  {
        image: url(ressources/images/folder_opened.png);
        background-color:rgba(_low_level_widget_color_, 110)
}
QTreeView, QTreeWidget {
    show-decoration-selected: 0;
}

QTreeView::branch {
    background-color: transparent;
}

QTreeView::branch:selected {
    background-color: transparent;
    color: rgb(_text_color_);
}

QTreeView::branch:!selected {
    background-color: transparent;
}

QTreeView::branch:hover {
   background-color: transparent;
}

.QFrame{
	background-color: rgb(_middle_level_widget_color_);
	margin:0px;
	border-radius:0px;
}

.QPushButton {
	background-color: rgb(_top_level_widget_color_);
	height:24px;
}
#exit_pushButton, #minimize_pushButton{
	border-radius: 10px;
	height :20px;
	width :20px;
}
#exit_pushButton{
	background-color:transparent;
	image: url(ressources/images/close.png);
}

#exit_pushButton:hover{
	image: url(ressources/images/closehover.png);
}

#minimize_pushButton{
	background-color:transparent;
	image: url(ressources/images/minimize.png);
}
#minimize_pushButton:hover{
	image: url(ressources/images/minimizehover.png);
}

QPushButton:hover {
	background-color: rgb(_hover_widget_color_);
}
QPushButton:pressed {
	background-color: rgb(_pressed_widget_color_);
}

QPushButton:checked {
	background-color: rgb(_pressed_widget_color_);
}

QComboBox,QSpinBox,QLineEdit, QDateTimeEdit{
	background-color: rgb(_low_level_widget_color_);
	height:24px;
	padding-left:10px;
}

QTextEdit{
	padding:10px;
}

QComboBox::drop-down, QSpinBox::up-button, QSpinBox::down-button, QDateTimeEdit::up-button, QDateTimeEdit::down-button
{
     width: 15px;
     color: rgb(_text_color_);
     padding-left: 10px;
	background-color: rgb(_low_level_widget_color_);
 }
QComboBox::down-arrow {
    border: 0px;
    background-repeat: no-repeat; 
	image: url(ressources/images/tree_arrow_down.png);
	width:20px;
	padding-right:10px;
}
QSpinBox::down-arrow,  QDateTimeEdit::down-arrow {
    border: 0px;
    background-repeat: no-repeat;
	 image: url(ressources/images/tree_arrow_down.png);
	width:20px;
	padding-right:9px;
}
QSpinBox::up-arrow,  QDateTimeEdit::up-arrow {
    border: 0px;
    background-repeat: no-repeat;
    image: url(ressources/images/up_arrow.png);
	width:20px;
	padding-right:9px;
}

QListView::item {
	height:22;
	padding:3px;
	border-radius:0px;	
	margin: 1px;
	background-color:rgba(255,255,255,4);
	color:white;
}

QListView::item:hover {
	padding:3px;
	background-color: rgb(_tree_hover_item_color_);
	border-radius:0px;	
	color:white;
}

QListView::item:selected {
	padding:3px;
	background-color: rgb(_tree_press_item_color_);
	color:white;
}

QListView::item:selected:active{
	padding:3px;
	background-color: rgb(_tree_press_item_color_);
	color:white;
}

QComboBox::drop-down:hover, QSpinBox::up-button:hover, QSpinBox::down-button:hover, QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover
{
	background-color: rgb(_hover_widget_color_);
 }
QComboBox::drop-down:pressed, QSpinBox::up-button:pressed, QSpinBox::down-button:pressed, QDateTimeEdit::up-button:pressed, QDateTimeEdit::down-button:pressed
{
	background-color: rgb(_pressed_widget_color_);
 }
QSpinBox::up-button, QDateTimeEdit::up-button {
     border-top-right-radius: 2px;
}
QSpinBox::down-button, QDateTimeEdit::down-button {
     border-bottom-right-radius: 2px;
}
QComboBox::drop-down{
     border-top-right-radius: 2px; /* same radius as the QComboBox */
     border-bottom-right-radius: 2px;
}
QSlider::groove:horizontal {
    border: 0px solid;
    height: 4px;
    background-color: rgb(_background_color_);
    margin: 2px 0;
}
QSlider::handle:horizontal {
	background-color: rgb(_background_color_);
    border: 0px solid;
    width: 12px;
    margin: -4px 0;
    border-radius: 5px;
}
.QCheckBox {
    spacing: 6px;
    background-color:transparent;
}

.QCheckBox:disabled{
	color: gray;
}

QCheckBox::indicator, QGroupBox::indicator {
    width: 13px;
    height: 13px;
	background-color: rgb(_background_color_);
}
QCheckBox::indicator:checked, QGroupBox::indicator:checked{
	border: 3px solid; 
	border-color: rgb(_background_color_);
	background-color: white;
	width: 7px; 
	height: 7px; 
}

QCheckBox::indicator:checked:disabled, QGroupBox::indicator:checked:disabled{
	background-color: gray;
}

QRadioButton{
	background-color:transparent;
}

QRadioButton::indicator {
	width: 12px;
	height: 12px;
	border-radius: 5px;
}

QRadioButton::indicator::unchecked{ 
	border: 1px solid;
	border-color: rgb(_background_color_);
	border-radius: 5px;
	background-color: rgb(_background_color_);
	width: 11px; 
	height: 11px;
}

QRadioButton::indicator::checked{ 
	border: 3px solid; 
	border-color: rgb(_background_color_);
	border-radius: 6px;
	background-color: rgb(_text_color_);
	width: 7px; 
	height: 7px; 
}

QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal,QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {
    background: none;

}

QScrollBar:horizontal {
    border: 0px solid grey;
	background-color: rgb(_background_color_);
    height: 15px;
    margin: 0px 20px 0 20px;

}
QScrollBar::handle:horizontal {
	background-color: rgb(_top_level_widget_color_);
    min-width: 20px;
}
QScrollBar::add-line:horizontal,QScrollBar::sub-line:horizontal {
    border: 0px solid grey;
	background-color: rgb(_background_color_);
    width: 20px;
    subcontrol-position: right;
    subcontrol-origin: margin;
}
QScrollBar::sub-line:horizontal {
    border: 0px solid grey;
	background-color: rgb(_background_color_);
    width: 20px;
    subcontrol-position: left;
    subcontrol-origin: margin;
}
QScrollBar:vertical {
    border: 0px solid grey;
    border-radius : 2px;
	background-color: rgb(_background_color_);
    width: 8px;
    margin: 0px 0px 0px 0px;
}
QScrollBar::handle:vertical {
	background-color: rgb(_top_level_widget_color_);
	border-radius : 4px;
}
QScrollBar::add-line:vertical,QScrollBar::sub-line:vertical {
    border: 0px solid grey;
	background-color:  rgb(_background_color_);
    height: 0px;
    subcontrol-position: top;
    subcontrol-origin: margin;
}

QScrollBar::sub-line:vertical {
    border: 0px solid grey;
	background-color: rgb(_background_color_);
    height: 0px;
    subcontrol-position: bottom;
    subcontrol-origin: margin;
}

QProgressBar {
	background-color:rgb(_background_color_);
    border: 0px solid grey;
    border-radius: 2px;
}

QProgressBar::chunk {
	background-color:gray;
	border-radius:2px;
}
QProgressBar {
    border-radius: 2px;
    text-align: center;
}
QTabWidget::pane { /* The tab widget frame */
	background-color : rgb(_background_color_);
}

 QTabBar::close-button {
     image: url(ressources/images/close_tab.png)
 }
 QTabBar::close-button:hover {
     image: url(ressources/images/close_tab_hover.png)
 }

QTabWidget::tab-bar {
    background-color : rgb(_background_color_);
}

/* Style the tab using the tab sub-control. Note that
    it reads QTabBar _not_ QTabWidget */
QTabBar::tab {
	border-bottom:2px solid rgb(_middle_level_widget_color_);
	background-color: rgb(_middle_level_widget_color_);
    min-width: 80px;
    padding: 7px;
    color : gray;
    margin-right:1px;
}
QTabBar::tab:selected{
	border-bottom:2px solid gray;
	color:white;
} 

QTabBar::tab:hover {
	border-bottom:2px solid white;
}

QTableView {
    selection-background-color: rgb(219,219,219);
}
QTableView::indicator:unchecked {
    background-color: #d7d6d5
}
QTableView QTableCornerButton::section {
	background-color: rgb(_background_color_);
}
QTableView QHeaderView::section
    {
	background-color: rgb(219,219,219);
    border:1px solid gray;
    }
QTableView QHeaderView::section::checked{
	background-color: rgb(_background_color_);
}
QMenu {
	background-color: rgb(_background_color_);
    margin: 2px; /* some spacing around the menu */

}
QMenu::item {
    padding: 2px 25px 2px 20px;
    border: 1px solid transparent; /* reserve space for selection border */
}
QMenu::item:selected {
	background-color: rgb(_hover_widget_color_);
}
QMenu::icon:checked { /* appearance of a 'checked' icon */
    background: gray;
    border: 1px inset gray;
    position: absolute;
    top: 1px;
    right: 1px;
    bottom: 1px;
    left: 1px;
}
QMenu::separator {
    height: 1px;
	background-color: rgb(_background_color_);
}

QMenu::indicator {
    width: 13px;
    height: 13px;
}

QMenuBar {
	padding:3px;
}

QMenuBar::item {
    spacing: 6px; /* spacing between menu bar items */
    padding: 4px 10px;
	height:10px;
    background: transparent;
    border-radius: 1px;
}
QMenuBar::item:selected { 
	background-color: rgb(_hover_widget_color_);	
}

QSplitter::handle {
    image: url(ressources/images/split_handle.png);
}