# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\ui_files\chat_house.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(583, 595)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chat_house_rooms_frame = QtWidgets.QFrame(Form)
        self.chat_house_rooms_frame.setMinimumSize(QtCore.QSize(60, 0))
        self.chat_house_rooms_frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.chat_house_rooms_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_house_rooms_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_house_rooms_frame.setObjectName("chat_house_rooms_frame")
        self.frame_layout = QtWidgets.QVBoxLayout(self.chat_house_rooms_frame)
        self.frame_layout.setContentsMargins(5, 5, 5, 5)
        self.frame_layout.setSpacing(1)
        self.frame_layout.setObjectName("frame_layout")
        self.chat_house_rooms_frame_layout = QtWidgets.QVBoxLayout()
        self.chat_house_rooms_frame_layout.setObjectName("chat_house_rooms_frame_layout")
        self.frame_layout.addLayout(self.chat_house_rooms_frame_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frame_layout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.chat_house_rooms_frame)
        self.chat_house_stackedWidget = QtWidgets.QStackedWidget(Form)
        self.chat_house_stackedWidget.setObjectName("chat_house_stackedWidget")
        self.horizontalLayout.addWidget(self.chat_house_stackedWidget)

        self.retranslateUi(Form)
        self.chat_house_stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
