# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\ui_files\chat_house.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(583, 595)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.chat_house_rooms_frame = QtWidgets.QFrame(self.splitter)
        self.chat_house_rooms_frame.setMinimumSize(QtCore.QSize(150, 0))
        self.chat_house_rooms_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_house_rooms_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_house_rooms_frame.setObjectName("chat_house_rooms_frame")
        self.frame_layout = QtWidgets.QVBoxLayout(self.chat_house_rooms_frame)
        self.frame_layout.setContentsMargins(0, 0, 0, 0)
        self.frame_layout.setSpacing(8)
        self.frame_layout.setObjectName("frame_layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.chat_house_rooms_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.create_room_pushButton = QtWidgets.QPushButton(self.chat_house_rooms_frame)
        self.create_room_pushButton.setMinimumSize(QtCore.QSize(26, 26))
        self.create_room_pushButton.setMaximumSize(QtCore.QSize(26, 26))
        self.create_room_pushButton.setStyleSheet("border-radius:13px;")
        self.create_room_pushButton.setObjectName("create_room_pushButton")
        self.horizontalLayout_2.addWidget(self.create_room_pushButton)
        self.frame_layout.addLayout(self.horizontalLayout_2)
        self.chat_house_rooms_frame_layout = QtWidgets.QVBoxLayout()
        self.chat_house_rooms_frame_layout.setSpacing(1)
        self.chat_house_rooms_frame_layout.setObjectName("chat_house_rooms_frame_layout")
        self.frame_layout.addLayout(self.chat_house_rooms_frame_layout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(8, 0, 8, -1)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.chat_house_rooms_frame)
        self.label.setMinimumSize(QtCore.QSize(0, 26))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.frame_layout.addLayout(self.horizontalLayout_3)
        self.chat_house_users_frame_layout = QtWidgets.QVBoxLayout()
        self.chat_house_users_frame_layout.setSpacing(1)
        self.chat_house_users_frame_layout.setObjectName("chat_house_users_frame_layout")
        self.frame_layout.addLayout(self.chat_house_users_frame_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.frame_layout.addItem(spacerItem)
        self.chat_house_stackedWidget = QtWidgets.QStackedWidget(self.splitter)
        self.chat_house_stackedWidget.setMinimumSize(QtCore.QSize(350, 0))
        self.chat_house_stackedWidget.setObjectName("chat_house_stackedWidget")
        self.verticalLayout.addWidget(self.splitter)

        self.retranslateUi(Form)
        self.chat_house_stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Rooms"))
        self.create_room_pushButton.setText(_translate("Form", "+"))
        self.label.setText(_translate("Form", "Users"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
