# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\gui\ui_files\chat.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(428, 544)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chat_frame = QtWidgets.QFrame(Form)
        self.chat_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_frame.setObjectName("chat_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.chat_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_top_horizontalFrame = QtWidgets.QFrame(self.chat_frame)
        self.chat_top_horizontalFrame.setObjectName("chat_top_horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.chat_top_horizontalFrame)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chat_project_label = QtWidgets.QLabel(self.chat_top_horizontalFrame)
        self.chat_project_label.setObjectName("chat_project_label")
        self.horizontalLayout.addWidget(self.chat_project_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.chat_top_horizontalFrame)
        self.messages_frame = QtWidgets.QFrame(self.chat_frame)
        self.messages_frame.setObjectName("messages_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.messages_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chat_main_scrollArea = QtWidgets.QScrollArea(self.messages_frame)
        self.chat_main_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chat_main_scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.chat_main_scrollArea.setWidgetResizable(True)
        self.chat_main_scrollArea.setObjectName("chat_main_scrollArea")
        self.chat_scrollAreaWidgetContents = QtWidgets.QWidget()
        self.chat_scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 424, 397))
        self.chat_scrollAreaWidgetContents.setObjectName("chat_scrollAreaWidgetContents")
        self.chat_messages_layouts = QtWidgets.QVBoxLayout(self.chat_scrollAreaWidgetContents)
        self.chat_messages_layouts.setContentsMargins(-1, 0, -1, 0)
        self.chat_messages_layouts.setObjectName("chat_messages_layouts")
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.chat_messages_layouts.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 11, -1, 11)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chat_show_more_pushButton = QtWidgets.QPushButton(self.chat_scrollAreaWidgetContents)
        self.chat_show_more_pushButton.setMinimumSize(QtCore.QSize(100, 40))
        self.chat_show_more_pushButton.setMaximumSize(QtCore.QSize(100, 40))
        self.chat_show_more_pushButton.setObjectName("chat_show_more_pushButton")
        self.horizontalLayout_3.addWidget(self.chat_show_more_pushButton)
        self.chat_messages_layouts.addLayout(self.horizontalLayout_3)
        self.chat_messages_layouts_1 = QtWidgets.QVBoxLayout()
        self.chat_messages_layouts_1.setSpacing(0)
        self.chat_messages_layouts_1.setObjectName("chat_messages_layouts_1")
        self.chat_messages_layouts.addLayout(self.chat_messages_layouts_1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 11, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.chat_messages_layouts.addItem(spacerItem2)
        self.chat_main_scrollArea.setWidget(self.chat_scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.chat_main_scrollArea)
        self.verticalLayout.addWidget(self.messages_frame)
        self.line_2 = QtWidgets.QFrame(self.chat_frame)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chat_file_frame = QtWidgets.QFrame(self.chat_frame)
        self.chat_file_frame.setObjectName("chat_file_frame")
        self.chat_file_layout = QtWidgets.QHBoxLayout(self.chat_file_frame)
        self.chat_file_layout.setObjectName("chat_file_layout")
        self.added_chat_file_pushButton = QtWidgets.QPushButton(self.chat_file_frame)
        self.added_chat_file_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.added_chat_file_pushButton.setText("")
        self.added_chat_file_pushButton.setObjectName("added_chat_file_pushButton")
        self.chat_file_layout.addWidget(self.added_chat_file_pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.chat_file_layout.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.chat_file_frame)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, -1, 0, -1)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_file_pushButton = QtWidgets.QPushButton(self.chat_frame)
        self.add_file_pushButton.setMinimumSize(QtCore.QSize(36, 36))
        self.add_file_pushButton.setMaximumSize(QtCore.QSize(36, 36))
        self.add_file_pushButton.setText("")
        self.add_file_pushButton.setObjectName("add_file_pushButton")
        self.horizontalLayout_4.addWidget(self.add_file_pushButton)
        self.send_message_pushButton = QtWidgets.QPushButton(self.chat_frame)
        self.send_message_pushButton.setMinimumSize(QtCore.QSize(36, 36))
        self.send_message_pushButton.setMaximumSize(QtCore.QSize(36, 36))
        self.send_message_pushButton.setText("")
        self.send_message_pushButton.setObjectName("send_message_pushButton")
        self.horizontalLayout_4.addWidget(self.send_message_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.chat_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chat_project_label.setText(_translate("Form", "TextLabel"))
        self.chat_show_more_pushButton.setText(_translate("Form", "Show more"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
