# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\ui_files\chat_message_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(903, 36)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(Form)
        self.main_frame.setStyleSheet("")
        self.main_frame.setObjectName("main_frame")
        self.chat_message_main_layout = QtWidgets.QHBoxLayout(self.main_frame)
        self.chat_message_main_layout.setContentsMargins(0, 0, 0, 0)
        self.chat_message_main_layout.setSpacing(10)
        self.chat_message_main_layout.setObjectName("chat_message_main_layout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setSpacing(1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.messages_frame = QtWidgets.QFrame(self.main_frame)
        self.messages_frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.messages_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.messages_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.messages_frame.setObjectName("messages_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.messages_frame)
        self.verticalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chat_message_text = QtWidgets.QLabel(self.messages_frame)
        self.chat_message_text.setWordWrap(True)
        self.chat_message_text.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.chat_message_text.setObjectName("chat_message_text")
        self.verticalLayout_2.addWidget(self.chat_message_text)
        self.verticalLayout_3.addWidget(self.messages_frame)
        self.chat_message_main_layout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.chat_message_main_layout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.main_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.chat_message_text.setText(_translate("Form", "message"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
