# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\exports_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 774)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.exports_main_frame = QtWidgets.QFrame(Form)
        self.exports_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.exports_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.exports_main_frame.setObjectName("exports_main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.exports_main_frame)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.exports_manager_header_Frame = QtWidgets.QFrame(self.exports_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exports_manager_header_Frame.sizePolicy().hasHeightForWidth())
        self.exports_manager_header_Frame.setSizePolicy(sizePolicy)
        self.exports_manager_header_Frame.setObjectName("exports_manager_header_Frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.exports_manager_header_Frame)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exports_manager_label = QtWidgets.QLabel(self.exports_manager_header_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exports_manager_label.sizePolicy().hasHeightForWidth())
        self.exports_manager_label.setSizePolicy(sizePolicy)
        self.exports_manager_label.setObjectName("exports_manager_label")
        self.horizontalLayout_3.addWidget(self.exports_manager_label)
        self.show_more_horizontalFrame = QtWidgets.QFrame(self.exports_manager_header_Frame)
        self.show_more_horizontalFrame.setObjectName("show_more_horizontalFrame")
        self.show_more_layout = QtWidgets.QHBoxLayout(self.show_more_horizontalFrame)
        self.show_more_layout.setContentsMargins(0, 0, 4, 0)
        self.show_more_layout.setSpacing(4)
        self.show_more_layout.setObjectName("show_more_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.show_more_layout.addItem(spacerItem)
        self.exports_number_label = QtWidgets.QLabel(self.show_more_horizontalFrame)
        self.exports_number_label.setText("")
        self.exports_number_label.setObjectName("exports_number_label")
        self.show_more_layout.addWidget(self.exports_number_label)
        self.show_more_pushButton = QtWidgets.QPushButton(self.show_more_horizontalFrame)
        self.show_more_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.show_more_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.show_more_pushButton.setObjectName("show_more_pushButton")
        self.show_more_layout.addWidget(self.show_more_pushButton)
        self.show_less_pushButton = QtWidgets.QPushButton(self.show_more_horizontalFrame)
        self.show_less_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.show_less_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.show_less_pushButton.setObjectName("show_less_pushButton")
        self.show_more_layout.addWidget(self.show_less_pushButton)
        self.horizontalLayout_3.addWidget(self.show_more_horizontalFrame)
        self.sanity_exports_pushButton = QtWidgets.QPushButton(self.exports_manager_header_Frame)
        self.sanity_exports_pushButton.setMinimumSize(QtCore.QSize(120, 28))
        self.sanity_exports_pushButton.setMaximumSize(QtCore.QSize(120, 28))
        self.sanity_exports_pushButton.setCheckable(True)
        self.sanity_exports_pushButton.setChecked(True)
        self.sanity_exports_pushButton.setObjectName("sanity_exports_pushButton")
        self.horizontalLayout_3.addWidget(self.sanity_exports_pushButton)
        self.show_all_exports_pushButton = QtWidgets.QPushButton(self.exports_manager_header_Frame)
        self.show_all_exports_pushButton.setMinimumSize(QtCore.QSize(100, 28))
        self.show_all_exports_pushButton.setMaximumSize(QtCore.QSize(120, 28))
        self.show_all_exports_pushButton.setCheckable(True)
        self.show_all_exports_pushButton.setObjectName("show_all_exports_pushButton")
        self.horizontalLayout_3.addWidget(self.show_all_exports_pushButton)
        self.verticalLayout_2.addWidget(self.exports_manager_header_Frame)
        self.exports_list_scrollArea = QtWidgets.QScrollArea(self.exports_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exports_list_scrollArea.sizePolicy().hasHeightForWidth())
        self.exports_list_scrollArea.setSizePolicy(sizePolicy)
        self.exports_list_scrollArea.setWidgetResizable(True)
        self.exports_list_scrollArea.setObjectName("exports_list_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 988, 642))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.export_list_verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.export_list_verticalLayout.setContentsMargins(0, 0, 5, 0)
        self.export_list_verticalLayout.setSpacing(0)
        self.export_list_verticalLayout.setObjectName("export_list_verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_verticalFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.list_verticalFrame.setObjectName("list_verticalFrame")
        self.export_list_verticalLayout_2 = QtWidgets.QVBoxLayout(self.list_verticalFrame)
        self.export_list_verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.export_list_verticalLayout_2.setSpacing(0)
        self.export_list_verticalLayout_2.setObjectName("export_list_verticalLayout_2")
        self.horizontalLayout_2.addWidget(self.list_verticalFrame)
        self.export_list_verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.export_list_verticalLayout.addItem(spacerItem1)
        self.exports_list_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.exports_list_scrollArea)
        self.manual_publish_horizontalFrame = QtWidgets.QFrame(self.exports_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manual_publish_horizontalFrame.sizePolicy().hasHeightForWidth())
        self.manual_publish_horizontalFrame.setSizePolicy(sizePolicy)
        self.manual_publish_horizontalFrame.setObjectName("manual_publish_horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.manual_publish_horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.batch_publish_pushButton = QtWidgets.QPushButton(self.manual_publish_horizontalFrame)
        self.batch_publish_pushButton.setMinimumSize(QtCore.QSize(150, 48))
        self.batch_publish_pushButton.setMaximumSize(QtCore.QSize(150, 48))
        self.batch_publish_pushButton.setObjectName("batch_publish_pushButton")
        self.horizontalLayout.addWidget(self.batch_publish_pushButton)
        self.manual_publish_pushButton = QtWidgets.QPushButton(self.manual_publish_horizontalFrame)
        self.manual_publish_pushButton.setMinimumSize(QtCore.QSize(210, 48))
        self.manual_publish_pushButton.setMaximumSize(QtCore.QSize(210, 48))
        self.manual_publish_pushButton.setObjectName("manual_publish_pushButton")
        self.horizontalLayout.addWidget(self.manual_publish_pushButton)
        self.verticalLayout_2.addWidget(self.manual_publish_horizontalFrame)
        self.verticalLayout.addWidget(self.exports_main_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.exports_manager_label.setText(_translate("Form", "Exports manager"))
        self.show_more_pushButton.setText(_translate("Form", "+3"))
        self.show_less_pushButton.setText(_translate("Form", "-3"))
        self.sanity_exports_pushButton.setText(_translate("Form", "Check sanity"))
        self.show_all_exports_pushButton.setText(_translate("Form", "Show all"))
        self.batch_publish_pushButton.setText(_translate("Form", "Batch export"))
        self.manual_publish_pushButton.setText(_translate("Form", "Manual export ( from files )"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
