# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\imported_asset_manager_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(421, 380)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.background_frame = QtWidgets.QFrame(Dialog)
        self.background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.background_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(self.background_frame)
        self.image_label.setMinimumSize(QtCore.QSize(50, 50))
        self.image_label.setText("")
        self.image_label.setObjectName("image_label")
        self.horizontalLayout.addWidget(self.image_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.imported_scene_label = QtWidgets.QLabel(self.background_frame)
        self.imported_scene_label.setObjectName("imported_scene_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.imported_scene_label)
        self.working_scene_label = QtWidgets.QLabel(self.background_frame)
        self.working_scene_label.setText("")
        self.working_scene_label.setObjectName("working_scene_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.working_scene_label)
        self.imported_variant_label = QtWidgets.QLabel(self.background_frame)
        self.imported_variant_label.setObjectName("imported_variant_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.imported_variant_label)
        self.variant_comboBox = QtWidgets.QComboBox(self.background_frame)
        self.variant_comboBox.setObjectName("variant_comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.variant_comboBox)
        self.imported_asset_label = QtWidgets.QLabel(self.background_frame)
        self.imported_asset_label.setObjectName("imported_asset_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.imported_asset_label)
        self.exported_asset_comboBox = QtWidgets.QComboBox(self.background_frame)
        self.exported_asset_comboBox.setObjectName("exported_asset_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.exported_asset_comboBox)
        self.imported_version_label = QtWidgets.QLabel(self.background_frame)
        self.imported_version_label.setObjectName("imported_version_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.imported_version_label)
        self.exported_version_comboBox = QtWidgets.QComboBox(self.background_frame)
        self.exported_version_comboBox.setObjectName("exported_version_comboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.exported_version_comboBox)
        self.imported_date_label = QtWidgets.QLabel(self.background_frame)
        self.imported_date_label.setObjectName("imported_date_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.imported_date_label)
        self.date_label = QtWidgets.QLabel(self.background_frame)
        self.date_label.setText("")
        self.date_label.setObjectName("date_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.date_label)
        self.imported_user_name_label = QtWidgets.QLabel(self.background_frame)
        self.imported_user_name_label.setObjectName("imported_user_name_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.imported_user_name_label)
        self.user_name_label = QtWidgets.QLabel(self.background_frame)
        self.user_name_label.setText("")
        self.user_name_label.setObjectName("user_name_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.user_name_label)
        self.imported_comment_label = QtWidgets.QLabel(self.background_frame)
        self.imported_comment_label.setObjectName("imported_comment_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.imported_comment_label)
        self.comment_label = QtWidgets.QLabel(self.background_frame)
        self.comment_label.setText("")
        self.comment_label.setObjectName("comment_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.comment_label)
        self.file_name_label = QtWidgets.QLabel(self.background_frame)
        self.file_name_label.setObjectName("file_name_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.file_name_label)
        self.file_label = QtWidgets.QLabel(self.background_frame)
        self.file_label.setText("")
        self.file_label.setObjectName("file_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.file_label)
        self.imported_namespace_label = QtWidgets.QLabel(self.background_frame)
        self.imported_namespace_label.setObjectName("imported_namespace_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.imported_namespace_label)
        self.namespace_label = QtWidgets.QLabel(self.background_frame)
        self.namespace_label.setText("")
        self.namespace_label.setObjectName("namespace_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.namespace_label)
        self.imported_software_label = QtWidgets.QLabel(self.background_frame)
        self.imported_software_label.setObjectName("imported_software_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.imported_software_label)
        self.software_label = QtWidgets.QLabel(self.background_frame)
        self.software_label.setText("")
        self.software_label.setObjectName("software_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.software_label)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.line_2 = QtWidgets.QFrame(self.background_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imported_asset_update_pushButton = QtWidgets.QPushButton(self.background_frame)
        self.imported_asset_update_pushButton.setObjectName("imported_asset_update_pushButton")
        self.horizontalLayout_2.addWidget(self.imported_asset_update_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.background_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.imported_scene_label.setText(_translate("Dialog", "Asset"))
        self.imported_variant_label.setText(_translate("Dialog", "Variant"))
        self.imported_asset_label.setText(_translate("Dialog", "Exported asset"))
        self.imported_version_label.setText(_translate("Dialog", "Export version"))
        self.imported_date_label.setText(_translate("Dialog", "Date"))
        self.imported_user_name_label.setText(_translate("Dialog", "User"))
        self.imported_comment_label.setText(_translate("Dialog", "Comment"))
        self.file_name_label.setText(_translate("Dialog", "File name"))
        self.imported_namespace_label.setText(_translate("Dialog", "Namespace"))
        self.imported_software_label.setText(_translate("Dialog", "Exported from"))
        self.imported_asset_update_pushButton.setText(_translate("Dialog", "Update"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
