# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leo\Documents\Script\Wizard\App\gui\ui_files\jokes_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(738, 152)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.jokes_widget_horizontalFrame = QtWidgets.QFrame(Form)
        self.jokes_widget_horizontalFrame.setObjectName("jokes_widget_horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.jokes_widget_horizontalFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previous_joke_pushButton = QtWidgets.QPushButton(self.jokes_widget_horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previous_joke_pushButton.sizePolicy().hasHeightForWidth())
        self.previous_joke_pushButton.setSizePolicy(sizePolicy)
        self.previous_joke_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.previous_joke_pushButton.setText("")
        self.previous_joke_pushButton.setObjectName("previous_joke_pushButton")
        self.horizontalLayout.addWidget(self.previous_joke_pushButton)
        self.jokes_main_verticalFrame = QtWidgets.QFrame(self.jokes_widget_horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jokes_main_verticalFrame.sizePolicy().hasHeightForWidth())
        self.jokes_main_verticalFrame.setSizePolicy(sizePolicy)
        self.jokes_main_verticalFrame.setStyleSheet("")
        self.jokes_main_verticalFrame.setObjectName("jokes_main_verticalFrame")
        self.main_verticalLayout = QtWidgets.QVBoxLayout(self.jokes_main_verticalFrame)
        self.main_verticalLayout.setObjectName("main_verticalLayout")
        self.jokes_layout = QtWidgets.QHBoxLayout()
        self.jokes_layout.setObjectName("jokes_layout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.jokes_layout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.high_quote_label = QtWidgets.QLabel(self.jokes_main_verticalFrame)
        self.high_quote_label.setMinimumSize(QtCore.QSize(40, 40))
        self.high_quote_label.setMaximumSize(QtCore.QSize(40, 40))
        self.high_quote_label.setText("")
        self.high_quote_label.setAlignment(QtCore.Qt.AlignCenter)
        self.high_quote_label.setObjectName("high_quote_label")
        self.verticalLayout_2.addWidget(self.high_quote_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.jokes_layout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.joke_label = QtWidgets.QLabel(self.jokes_main_verticalFrame)
        self.joke_label.setText("")
        self.joke_label.setAlignment(QtCore.Qt.AlignCenter)
        self.joke_label.setWordWrap(True)
        self.joke_label.setObjectName("joke_label")
        self.verticalLayout_4.addWidget(self.joke_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.jokes_layout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.low_quote_label = QtWidgets.QLabel(self.jokes_main_verticalFrame)
        self.low_quote_label.setMinimumSize(QtCore.QSize(40, 40))
        self.low_quote_label.setMaximumSize(QtCore.QSize(40, 40))
        self.low_quote_label.setText("")
        self.low_quote_label.setAlignment(QtCore.Qt.AlignCenter)
        self.low_quote_label.setObjectName("low_quote_label")
        self.verticalLayout_3.addWidget(self.low_quote_label)
        self.jokes_layout.addLayout(self.verticalLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.jokes_layout.addItem(spacerItem5)
        self.main_verticalLayout.addLayout(self.jokes_layout)
        self.infos_layout = QtWidgets.QHBoxLayout()
        self.infos_layout.setObjectName("infos_layout")
        self.votes_frame = QtWidgets.QFrame(self.jokes_main_verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.votes_frame.sizePolicy().hasHeightForWidth())
        self.votes_frame.setSizePolicy(sizePolicy)
        self.votes_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.votes_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.votes_frame.setObjectName("votes_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.votes_frame)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.star1_pushButton = QtWidgets.QPushButton(self.votes_frame)
        self.star1_pushButton.setMinimumSize(QtCore.QSize(18, 18))
        self.star1_pushButton.setMaximumSize(QtCore.QSize(18, 18))
        self.star1_pushButton.setText("")
        self.star1_pushButton.setObjectName("star1_pushButton")
        self.horizontalLayout_3.addWidget(self.star1_pushButton)
        self.star2_pushButton = QtWidgets.QPushButton(self.votes_frame)
        self.star2_pushButton.setMinimumSize(QtCore.QSize(18, 18))
        self.star2_pushButton.setMaximumSize(QtCore.QSize(18, 18))
        self.star2_pushButton.setText("")
        self.star2_pushButton.setObjectName("star2_pushButton")
        self.horizontalLayout_3.addWidget(self.star2_pushButton)
        self.star3_pushButton = QtWidgets.QPushButton(self.votes_frame)
        self.star3_pushButton.setMinimumSize(QtCore.QSize(18, 18))
        self.star3_pushButton.setMaximumSize(QtCore.QSize(18, 18))
        self.star3_pushButton.setText("")
        self.star3_pushButton.setObjectName("star3_pushButton")
        self.horizontalLayout_3.addWidget(self.star3_pushButton)
        self.star4_pushButton = QtWidgets.QPushButton(self.votes_frame)
        self.star4_pushButton.setMinimumSize(QtCore.QSize(18, 18))
        self.star4_pushButton.setMaximumSize(QtCore.QSize(18, 18))
        self.star4_pushButton.setText("")
        self.star4_pushButton.setObjectName("star4_pushButton")
        self.horizontalLayout_3.addWidget(self.star4_pushButton)
        self.star5_pushButton = QtWidgets.QPushButton(self.votes_frame)
        self.star5_pushButton.setMinimumSize(QtCore.QSize(18, 18))
        self.star5_pushButton.setMaximumSize(QtCore.QSize(18, 18))
        self.star5_pushButton.setText("")
        self.star5_pushButton.setObjectName("star5_pushButton")
        self.horizontalLayout_3.addWidget(self.star5_pushButton)
        self.infos_layout.addWidget(self.votes_frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.float_note_label = QtWidgets.QLabel(self.jokes_main_verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.float_note_label.sizePolicy().hasHeightForWidth())
        self.float_note_label.setSizePolicy(sizePolicy)
        self.float_note_label.setMinimumSize(QtCore.QSize(10, 0))
        self.float_note_label.setText("")
        self.float_note_label.setObjectName("float_note_label")
        self.verticalLayout.addWidget(self.float_note_label)
        self.infos_layout.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infos_layout.addItem(spacerItem6)
        self.user_jokes_pushButton = QtWidgets.QPushButton(self.jokes_main_verticalFrame)
        self.user_jokes_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.user_jokes_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.user_jokes_pushButton.setText("")
        self.user_jokes_pushButton.setObjectName("user_jokes_pushButton")
        self.infos_layout.addWidget(self.user_jokes_pushButton)
        self.add_joke_pushButton = QtWidgets.QPushButton(self.jokes_main_verticalFrame)
        self.add_joke_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.add_joke_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.add_joke_pushButton.setText("")
        self.add_joke_pushButton.setObjectName("add_joke_pushButton")
        self.infos_layout.addWidget(self.add_joke_pushButton)
        self.main_verticalLayout.addLayout(self.infos_layout)
        self.horizontalLayout.addWidget(self.jokes_main_verticalFrame)
        self.next_joke_pushButton = QtWidgets.QPushButton(self.jokes_widget_horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_joke_pushButton.sizePolicy().hasHeightForWidth())
        self.next_joke_pushButton.setSizePolicy(sizePolicy)
        self.next_joke_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.next_joke_pushButton.setText("")
        self.next_joke_pushButton.setObjectName("next_joke_pushButton")
        self.horizontalLayout.addWidget(self.next_joke_pushButton)
        self.horizontalLayout_2.addWidget(self.jokes_widget_horizontalFrame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

