# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leo\Documents\Script\Wizard\App\gui\ui_files\log_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_log_widget(object):
    def setupUi(self, log_widget):
        log_widget.setObjectName("log_widget")
        log_widget.resize(1066, 721)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(log_widget.sizePolicy().hasHeightForWidth())
        log_widget.setSizePolicy(sizePolicy)
        log_widget.setMinimumSize(QtCore.QSize(550, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(log_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(log_widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log_textEdit = QtWidgets.QTextEdit(self.frame)
        self.log_textEdit.setReadOnly(True)
        self.log_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.log_textEdit.setObjectName("log_textEdit")
        self.verticalLayout_2.addWidget(self.log_textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.log_execute_pushButton = QtWidgets.QPushButton(self.frame)
        self.log_execute_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.log_execute_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.log_execute_pushButton.setText("")
        self.log_execute_pushButton.setObjectName("log_execute_pushButton")
        self.horizontalLayout.addWidget(self.log_execute_pushButton)
        self.log_clear_pushButton = QtWidgets.QPushButton(self.frame)
        self.log_clear_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.log_clear_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.log_clear_pushButton.setText("")
        self.log_clear_pushButton.setObjectName("log_clear_pushButton")
        self.horizontalLayout.addWidget(self.log_clear_pushButton)
        self.log_report_pushButton = QtWidgets.QPushButton(self.frame)
        self.log_report_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.log_report_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.log_report_pushButton.setText("")
        self.log_report_pushButton.setObjectName("log_report_pushButton")
        self.horizontalLayout.addWidget(self.log_report_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 3, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1052, 192))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_py_script = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_py_script.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_py_script.setSpacing(0)
        self.horizontalLayout_py_script.setObjectName("horizontalLayout_py_script")
        self.log_lines_plainTextEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.log_lines_plainTextEdit.setMaximumSize(QtCore.QSize(45, 200))
        self.log_lines_plainTextEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.log_lines_plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.log_lines_plainTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.log_lines_plainTextEdit.setTabChangesFocus(True)
        self.log_lines_plainTextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.log_lines_plainTextEdit.setObjectName("log_lines_plainTextEdit")
        self.horizontalLayout_py_script.addWidget(self.log_lines_plainTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(log_widget)
        log_widget.destroyed.connect(log_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(log_widget)

    def retranslateUi(self, log_widget):
        _translate = QtCore.QCoreApplication.translate
        log_widget.setWindowTitle(_translate("log_widget", "Form"))
        self.log_lines_plainTextEdit.setPlainText(_translate("log_widget", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    log_widget = QtWidgets.QWidget()
    ui = Ui_log_widget()
    ui.setupUi(log_widget)
    log_widget.show()
    sys.exit(app.exec_())

