# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\ui_files\log_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_log_widget(object):
    def setupUi(self, log_widget):
        log_widget.setObjectName("log_widget")
        log_widget.resize(1066, 721)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(log_widget.sizePolicy().hasHeightForWidth())
        log_widget.setSizePolicy(sizePolicy)
        log_widget.setMinimumSize(QtCore.QSize(550, 0))
        self.verticalLayout = QtWidgets.QVBoxLayout(log_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(log_widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log_textEdit = QtWidgets.QTextEdit(self.frame)
        self.log_textEdit.setReadOnly(True)
        self.log_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.log_textEdit.setObjectName("log_textEdit")
        self.verticalLayout_2.addWidget(self.log_textEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.log_execute_pushButton = QtWidgets.QPushButton(self.frame)
        self.log_execute_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.log_execute_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.log_execute_pushButton.setText("")
        self.log_execute_pushButton.setObjectName("log_execute_pushButton")
        self.horizontalLayout.addWidget(self.log_execute_pushButton)
        self.log_clear_pushButton = QtWidgets.QPushButton(self.frame)
        self.log_clear_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.log_clear_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.log_clear_pushButton.setText("")
        self.log_clear_pushButton.setObjectName("log_clear_pushButton")
        self.horizontalLayout.addWidget(self.log_clear_pushButton)
        self.log_report_pushButton = QtWidgets.QPushButton(self.frame)
        self.log_report_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.log_report_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.log_report_pushButton.setText("")
        self.log_report_pushButton.setObjectName("log_report_pushButton")
        self.horizontalLayout.addWidget(self.log_report_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 3, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.python_0 = QtWidgets.QWidget()
        self.python_0.setObjectName("python_0")
        self.script_editor_layout = QtWidgets.QVBoxLayout(self.python_0)
        self.script_editor_layout.setContentsMargins(0, 10, 0, 0)
        self.script_editor_layout.setSpacing(0)
        self.script_editor_layout.setObjectName("script_editor_layout")
        self.tabWidget.addTab(self.python_0, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(log_widget)
        self.tabWidget.setCurrentIndex(0)
        log_widget.destroyed.connect(log_widget.hide)
        QtCore.QMetaObject.connectSlotsByName(log_widget)

    def retranslateUi(self, log_widget):
        _translate = QtCore.QCoreApplication.translate
        log_widget.setWindowTitle(_translate("log_widget", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.python_0), _translate("log_widget", "Python"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    log_widget = QtWidgets.QWidget()
    ui = Ui_log_widget()
    ui.setupUi(log_widget)
    log_widget.show()
    sys.exit(app.exec_())
