# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\gui\ui_files\message_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(246, 100)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.message_main_frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_main_frame.sizePolicy().hasHeightForWidth())
        self.message_main_frame.setSizePolicy(sizePolicy)
        self.message_main_frame.setObjectName("message_main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.message_main_frame)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.message_widget_image_layout = QtWidgets.QFrame(self.message_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_widget_image_layout.sizePolicy().hasHeightForWidth())
        self.message_widget_image_layout.setSizePolicy(sizePolicy)
        self.message_widget_image_layout.setObjectName("message_widget_image_layout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.message_widget_image_layout)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.message_widget_image_label = QtWidgets.QPushButton(self.message_widget_image_layout)
        self.message_widget_image_label.setMinimumSize(QtCore.QSize(38, 38))
        self.message_widget_image_label.setMaximumSize(QtCore.QSize(38, 38))
        self.message_widget_image_label.setText("")
        self.message_widget_image_label.setIconSize(QtCore.QSize(38, 38))
        self.message_widget_image_label.setObjectName("message_widget_image_label")
        self.verticalLayout_2.addWidget(self.message_widget_image_label)
        self.message_widget_spacer_frame = QtWidgets.QFrame(self.message_widget_image_layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_widget_spacer_frame.sizePolicy().hasHeightForWidth())
        self.message_widget_spacer_frame.setSizePolicy(sizePolicy)
        self.message_widget_spacer_frame.setObjectName("message_widget_spacer_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.message_widget_spacer_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2.addWidget(self.message_widget_spacer_frame)
        self.horizontalLayout.addWidget(self.message_widget_image_layout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.message_user_label = QtWidgets.QLabel(self.message_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_user_label.sizePolicy().hasHeightForWidth())
        self.message_user_label.setSizePolicy(sizePolicy)
        self.message_user_label.setText("")
        self.message_user_label.setObjectName("message_user_label")
        self.verticalLayout.addWidget(self.message_user_label)
        self.chat_file_pushButton = QtWidgets.QPushButton(self.message_main_frame)
        self.chat_file_pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.chat_file_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chat_file_pushButton.setText("")
        self.chat_file_pushButton.setObjectName("chat_file_pushButton")
        self.verticalLayout.addWidget(self.chat_file_pushButton)
        self.message_widget_label = QtWidgets.QLabel(self.message_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.message_widget_label.sizePolicy().hasHeightForWidth())
        self.message_widget_label.setSizePolicy(sizePolicy)
        self.message_widget_label.setText("")
        self.message_widget_label.setWordWrap(True)
        self.message_widget_label.setOpenExternalLinks(True)
        self.message_widget_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.message_widget_label.setObjectName("message_widget_label")
        self.verticalLayout.addWidget(self.message_widget_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.message_main_frame)
        spacerItem1 = QtWidgets.QSpacerItem(30, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
