# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\new_user_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(428, 678)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.new_user_label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_user_label.sizePolicy().hasHeightForWidth())
        self.new_user_label.setSizePolicy(sizePolicy)
        self.new_user_label.setObjectName("new_user_label")
        self.verticalLayout_4.addWidget(self.new_user_label)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.avatar_pushButton = QtWidgets.QPushButton(self.frame)
        self.avatar_pushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.avatar_pushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.avatar_pushButton.setText("")
        self.avatar_pushButton.setObjectName("avatar_pushButton")
        self.verticalLayout.addWidget(self.avatar_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        self.new_user_warning_label = QtWidgets.QLabel(self.frame)
        self.new_user_warning_label.setObjectName("new_user_warning_label")
        self.verticalLayout.addWidget(self.new_user_warning_label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.new_user_name_label = QtWidgets.QLabel(self.frame)
        self.new_user_name_label.setObjectName("new_user_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.new_user_name_label)
        self.user_name_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.user_name_lineEdit.setObjectName("user_name_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.user_name_lineEdit)
        self.password_label = QtWidgets.QLabel(self.frame)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.user_email_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.user_email_lineEdit.setObjectName("user_email_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.user_email_lineEdit)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.confirm_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.confirm_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirm_lineEdit.setObjectName("confirm_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.confirm_lineEdit)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.password_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.password_lineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.horizontalLayout.addWidget(self.password_lineEdit)
        self.show_pass_pushButton = QtWidgets.QPushButton(self.frame)
        self.show_pass_pushButton.setMinimumSize(QtCore.QSize(22, 22))
        self.show_pass_pushButton.setMaximumSize(QtCore.QSize(22, 22))
        self.show_pass_pushButton.setText("")
        self.show_pass_pushButton.setObjectName("show_pass_pushButton")
        self.horizontalLayout.addWidget(self.show_pass_pushButton)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.class_comboBox = QtWidgets.QComboBox(self.frame)
        self.class_comboBox.setMinimumSize(QtCore.QSize(0, 22))
        self.class_comboBox.setObjectName("class_comboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.class_comboBox)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.full_name_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.full_name_lineEdit.setObjectName("full_name_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.full_name_lineEdit)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem3)
        self.admin_checkBox = QtWidgets.QCheckBox(self.frame)
        self.admin_checkBox.setMinimumSize(QtCore.QSize(0, 30))
        self.admin_checkBox.setObjectName("admin_checkBox")
        self.verticalLayout.addWidget(self.admin_checkBox)
        self.create_user_button = QtWidgets.QPushButton(self.frame)
        self.create_user_button.setMinimumSize(QtCore.QSize(0, 70))
        self.create_user_button.setMaximumSize(QtCore.QSize(16777215, 70))
        self.create_user_button.setObjectName("create_user_button")
        self.verticalLayout.addWidget(self.create_user_button)
        self.verticalLayout_2.addWidget(self.frame)
        self.log_frame = QtWidgets.QFrame(Dialog)
        self.log_frame.setObjectName("log_frame")
        self.log_layout = QtWidgets.QHBoxLayout(self.log_frame)
        self.log_layout.setContentsMargins(0, 0, 0, 0)
        self.log_layout.setSpacing(0)
        self.log_layout.setObjectName("log_layout")
        self.log_lineEdit = QtWidgets.QLineEdit(self.log_frame)
        self.log_lineEdit.setReadOnly(True)
        self.log_lineEdit.setObjectName("log_lineEdit")
        self.log_layout.addWidget(self.log_lineEdit)
        self.verticalLayout_2.addWidget(self.log_frame)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.new_user_label.setText(_translate("Dialog", "Create new user"))
        self.new_user_warning_label.setText(_translate("Dialog", "Please KEEP your session name"))
        self.new_user_name_label.setText(_translate("Dialog", "User name"))
        self.password_label.setText(_translate("Dialog", "Password"))
        self.user_email_lineEdit.setPlaceholderText(_translate("Dialog", "jean.dupont@gmail.com"))
        self.label.setText(_translate("Dialog", "Email"))
        self.label_2.setText(_translate("Dialog", "Confirm"))
        self.label_3.setText(_translate("Dialog", "Class"))
        self.full_name_lineEdit.setPlaceholderText(_translate("Dialog", "Jean Dupont"))
        self.label_4.setText(_translate("Dialog", "Full name"))
        self.admin_checkBox.setText(_translate("Dialog", "Administrator"))
        self.create_user_button.setText(_translate("Dialog", "Create user"))
        self.log_lineEdit.setPlaceholderText(_translate("Dialog", "Warnings and logs here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
