# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\leo\Documents\Script\Wizard\App\gui\ui_files\node_editor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NodeEditorWidget(object):
    def setupUi(self, NodeEditorWidget):
        NodeEditorWidget.setObjectName("NodeEditorWidget")
        NodeEditorWidget.resize(800, 719)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(NodeEditorWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.node_editor_frame = QtWidgets.QFrame(NodeEditorWidget)
        self.node_editor_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.node_editor_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node_editor_frame.setObjectName("node_editor_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.node_editor_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scene_manager_label = QtWidgets.QLabel(self.node_editor_frame)
        self.scene_manager_label.setObjectName("scene_manager_label")
        self.verticalLayout_4.addWidget(self.scene_manager_label)
        self.node_editor_scrollArea = QtWidgets.QScrollArea(self.node_editor_frame)
        self.node_editor_scrollArea.setStyleSheet("")
        self.node_editor_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.node_editor_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.node_editor_scrollArea.setWidgetResizable(True)
        self.node_editor_scrollArea.setObjectName("node_editor_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 774, 670))
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.arrow_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrow_label.sizePolicy().hasHeightForWidth())
        self.arrow_label.setSizePolicy(sizePolicy)
        self.arrow_label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.arrow_label.setText("")
        self.arrow_label.setAlignment(QtCore.Qt.AlignCenter)
        self.arrow_label.setObjectName("arrow_label")
        self.verticalLayout.addWidget(self.arrow_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.references_number_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.references_number_frame.setMinimumSize(QtCore.QSize(20, 0))
        self.references_number_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.references_number_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.references_number_frame.setObjectName("references_number_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.references_number_frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.references_number_label = QtWidgets.QLabel(self.references_number_frame)
        self.references_number_label.setObjectName("references_number_label")
        self.horizontalLayout_5.addWidget(self.references_number_label)
        self.horizontalLayout_4.addWidget(self.references_number_frame)
        self.node_editor_buttons_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.node_editor_buttons_frame.setMinimumSize(QtCore.QSize(0, 20))
        self.node_editor_buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.node_editor_buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.node_editor_buttons_frame.setObjectName("node_editor_buttons_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.node_editor_buttons_frame)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.update_all_pushButton = QtWidgets.QPushButton(self.node_editor_buttons_frame)
        self.update_all_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.update_all_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.update_all_pushButton.setText("")
        self.update_all_pushButton.setObjectName("update_all_pushButton")
        self.horizontalLayout_3.addWidget(self.update_all_pushButton)
        self.trash_pushButton = QtWidgets.QPushButton(self.node_editor_buttons_frame)
        self.trash_pushButton.setMinimumSize(QtCore.QSize(28, 28))
        self.trash_pushButton.setMaximumSize(QtCore.QSize(28, 28))
        self.trash_pushButton.setText("")
        self.trash_pushButton.setObjectName("trash_pushButton")
        self.horizontalLayout_3.addWidget(self.trash_pushButton)
        self.horizontalLayout_4.addWidget(self.node_editor_buttons_frame)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.node_editor_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.node_editor_scrollArea)
        self.verticalLayout_2.addWidget(self.node_editor_frame)

        self.retranslateUi(NodeEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(NodeEditorWidget)

    def retranslateUi(self, NodeEditorWidget):
        _translate = QtCore.QCoreApplication.translate
        NodeEditorWidget.setWindowTitle(_translate("NodeEditorWidget", "Form"))
        self.scene_manager_label.setText(_translate("NodeEditorWidget", "Scene manager"))
        self.references_number_label.setText(_translate("NodeEditorWidget", "0 references"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NodeEditorWidget = QtWidgets.QWidget()
    ui = Ui_NodeEditorWidget()
    ui.setupUi(NodeEditorWidget)
    NodeEditorWidget.show()
    sys.exit(app.exec_())

