# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\preferences.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(439, 695)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_12 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.screens_comboBox = QtWidgets.QComboBox(self.frame_4)
        self.screens_comboBox.setObjectName("screens_comboBox")
        self.horizontalLayout_6.addWidget(self.screens_comboBox)
        self.verticalLayout_9.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame)
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.shutter_checkBox = QtWidgets.QCheckBox(self.frame_7)
        self.shutter_checkBox.setObjectName("shutter_checkBox")
        self.verticalLayout_5.addWidget(self.shutter_checkBox)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_5 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 244))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.popup_enable_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.popup_enable_checkBox.setChecked(True)
        self.popup_enable_checkBox.setAutoRepeat(False)
        self.popup_enable_checkBox.setObjectName("popup_enable_checkBox")
        self.verticalLayout_10.addWidget(self.popup_enable_checkBox)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.popup_sound_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.popup_sound_checkBox.setChecked(True)
        self.popup_sound_checkBox.setObjectName("popup_sound_checkBox")
        self.horizontalLayout_3.addWidget(self.popup_sound_checkBox)
        self.popup_sounds_comboBox = QtWidgets.QComboBox(self.frame_5)
        self.popup_sounds_comboBox.setObjectName("popup_sounds_comboBox")
        self.horizontalLayout_3.addWidget(self.popup_sounds_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        self.popup_position_comboBox = QtWidgets.QComboBox(self.frame_5)
        self.popup_position_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.popup_position_comboBox.setObjectName("popup_position_comboBox")
        self.horizontalLayout_7.addWidget(self.popup_position_comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.popup_duration_spinBox = QtWidgets.QSpinBox(self.frame_5)
        self.popup_duration_spinBox.setMinimum(1)
        self.popup_duration_spinBox.setObjectName("popup_duration_spinBox")
        self.horizontalLayout_8.addWidget(self.popup_duration_spinBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.popup_creation_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.popup_creation_checkBox.setChecked(True)
        self.popup_creation_checkBox.setObjectName("popup_creation_checkBox")
        self.verticalLayout_10.addWidget(self.popup_creation_checkBox)
        self.popup_publish_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.popup_publish_checkBox.setChecked(True)
        self.popup_publish_checkBox.setObjectName("popup_publish_checkBox")
        self.verticalLayout_10.addWidget(self.popup_publish_checkBox)
        self.popup_save_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.popup_save_checkBox.setChecked(True)
        self.popup_save_checkBox.setObjectName("popup_save_checkBox")
        self.verticalLayout_10.addWidget(self.popup_save_checkBox)
        self.popup_message_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.popup_message_checkBox.setChecked(True)
        self.popup_message_checkBox.setObjectName("popup_message_checkBox")
        self.verticalLayout_10.addWidget(self.popup_message_checkBox)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.versions_updates_checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.versions_updates_checkBox.setObjectName("versions_updates_checkBox")
        self.verticalLayout_2.addWidget(self.versions_updates_checkBox)
        self.new_version_checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.new_version_checkBox.setObjectName("new_version_checkBox")
        self.verticalLayout_2.addWidget(self.new_version_checkBox)
        self.error_handler_checkBox = QtWidgets.QCheckBox(self.frame_3)
        self.error_handler_checkBox.setObjectName("error_handler_checkBox")
        self.verticalLayout_2.addWidget(self.error_handler_checkBox)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setStyleSheet("color:gray;")
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.local_project_path_lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.local_project_path_lineEdit.setReadOnly(True)
        self.local_project_path_lineEdit.setObjectName("local_project_path_lineEdit")
        self.horizontalLayout.addWidget(self.local_project_path_lineEdit)
        self.local_folder_pushButton = QtWidgets.QPushButton(self.frame_6)
        self.local_folder_pushButton.setMinimumSize(QtCore.QSize(24, 24))
        self.local_folder_pushButton.setMaximumSize(QtCore.QSize(24, 24))
        self.local_folder_pushButton.setText("")
        self.local_folder_pushButton.setIconSize(QtCore.QSize(12, 12))
        self.local_folder_pushButton.setObjectName("local_folder_pushButton")
        self.horizontalLayout.addWidget(self.local_folder_pushButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_6)
        self.save_prefs_pushButton = QtWidgets.QPushButton(Form)
        self.save_prefs_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.save_prefs_pushButton.setMaximumSize(QtCore.QSize(16777215, 50))
        self.save_prefs_pushButton.setObjectName("save_prefs_pushButton")
        self.verticalLayout.addWidget(self.save_prefs_pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Preferences"))
        self.label_12.setText(_translate("Form", "Wizard position"))
        self.label_13.setText(_translate("Form", "Screen"))
        self.label_5.setText(_translate("Form", "Wizard as shutter"))
        self.shutter_checkBox.setText(_translate("Form", "Activated"))
        self.label_14.setText(_translate("Form", "Popup messages"))
        self.popup_enable_checkBox.setText(_translate("Form", "Enabled"))
        self.popup_sound_checkBox.setText(_translate("Form", "Sound"))
        self.label_15.setText(_translate("Form", "Position"))
        self.label_16.setText(_translate("Form", "Duration (s)"))
        self.popup_creation_checkBox.setText(_translate("Form", "Asset creation ( From all team )"))
        self.popup_publish_checkBox.setText(_translate("Form", "Publish event ( From all team )"))
        self.popup_save_checkBox.setText(_translate("Form", "Save Event ( Me only )"))
        self.popup_message_checkBox.setText(_translate("Form", "New message"))
        self.label_2.setText(_translate("Form", "General"))
        self.versions_updates_checkBox.setText(_translate("Form", "Show wizard version updates"))
        self.new_version_checkBox.setText(_translate("Form", "Show me the new wizard versions"))
        self.error_handler_checkBox.setText(_translate("Form", "Auto submit errors ( Hide the error handler dialog )"))
        self.label_3.setText(_translate("Form", "Local project path"))
        self.label_4.setText(_translate("Form", "Please choose an empty directory, you can set the same name as your project"))
        self.local_project_path_lineEdit.setPlaceholderText(_translate("Form", "D:/..."))
        self.save_prefs_pushButton.setText(_translate("Form", "Save and close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
