# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\quit_popup_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(285, 249)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame_2 = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame_2.sizePolicy().hasHeightForWidth())
        self.horizontalFrame_2.setSizePolicy(sizePolicy)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.quit_popup_warning_image_label = QtWidgets.QLabel(self.horizontalFrame_2)
        self.quit_popup_warning_image_label.setMinimumSize(QtCore.QSize(50, 50))
        self.quit_popup_warning_image_label.setMaximumSize(QtCore.QSize(50, 50))
        self.quit_popup_warning_image_label.setText("")
        self.quit_popup_warning_image_label.setObjectName("quit_popup_warning_image_label")
        self.horizontalLayout_2.addWidget(self.quit_popup_warning_image_label)
        self.label = QtWidgets.QLabel(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.horizontalFrame_2)
        self.quit_popup_lock_frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_popup_lock_frame.sizePolicy().hasHeightForWidth())
        self.quit_popup_lock_frame.setSizePolicy(sizePolicy)
        self.quit_popup_lock_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quit_popup_lock_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quit_popup_lock_frame.setObjectName("quit_popup_lock_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.quit_popup_lock_frame)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.quit_popup_lock_image_label = QtWidgets.QLabel(self.quit_popup_lock_frame)
        self.quit_popup_lock_image_label.setMinimumSize(QtCore.QSize(31, 31))
        self.quit_popup_lock_image_label.setMaximumSize(QtCore.QSize(31, 31))
        self.quit_popup_lock_image_label.setText("")
        self.quit_popup_lock_image_label.setObjectName("quit_popup_lock_image_label")
        self.horizontalLayout_5.addWidget(self.quit_popup_lock_image_label)
        self.quit_popup_lock_label = QtWidgets.QLabel(self.quit_popup_lock_frame)
        self.quit_popup_lock_label.setObjectName("quit_popup_lock_label")
        self.horizontalLayout_5.addWidget(self.quit_popup_lock_label)
        self.quit_popup_unlock_all_pushButton = QtWidgets.QPushButton(self.quit_popup_lock_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_popup_unlock_all_pushButton.sizePolicy().hasHeightForWidth())
        self.quit_popup_unlock_all_pushButton.setSizePolicy(sizePolicy)
        self.quit_popup_unlock_all_pushButton.setMinimumSize(QtCore.QSize(0, 31))
        self.quit_popup_unlock_all_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.quit_popup_unlock_all_pushButton.setObjectName("quit_popup_unlock_all_pushButton")
        self.horizontalLayout_5.addWidget(self.quit_popup_unlock_all_pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.quit_popup_lock_frame)
        self.quit_popup_run_frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_popup_run_frame.sizePolicy().hasHeightForWidth())
        self.quit_popup_run_frame.setSizePolicy(sizePolicy)
        self.quit_popup_run_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quit_popup_run_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quit_popup_run_frame.setObjectName("quit_popup_run_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.quit_popup_run_frame)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.quit_popup_run_image_label = QtWidgets.QLabel(self.quit_popup_run_frame)
        self.quit_popup_run_image_label.setMinimumSize(QtCore.QSize(31, 31))
        self.quit_popup_run_image_label.setMaximumSize(QtCore.QSize(31, 31))
        self.quit_popup_run_image_label.setText("")
        self.quit_popup_run_image_label.setObjectName("quit_popup_run_image_label")
        self.horizontalLayout_3.addWidget(self.quit_popup_run_image_label)
        self.quit_popup_run_label = QtWidgets.QLabel(self.quit_popup_run_frame)
        self.quit_popup_run_label.setObjectName("quit_popup_run_label")
        self.horizontalLayout_3.addWidget(self.quit_popup_run_label)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.quit_popup_run_frame)
        self.quit_popup_main_frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quit_popup_main_frame.sizePolicy().hasHeightForWidth())
        self.quit_popup_main_frame.setSizePolicy(sizePolicy)
        self.quit_popup_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quit_popup_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quit_popup_main_frame.setObjectName("quit_popup_main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.quit_popup_main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame = QtWidgets.QFrame(self.quit_popup_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalFrame.sizePolicy().hasHeightForWidth())
        self.horizontalFrame.setSizePolicy(sizePolicy)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.quit_popup_cancel_pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.quit_popup_cancel_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.quit_popup_cancel_pushButton.setDefault(True)
        self.quit_popup_cancel_pushButton.setObjectName("quit_popup_cancel_pushButton")
        self.horizontalLayout.addWidget(self.quit_popup_cancel_pushButton)
        self.quit_popup_quit_pushButton = QtWidgets.QPushButton(self.horizontalFrame)
        self.quit_popup_quit_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.quit_popup_quit_pushButton.setObjectName("quit_popup_quit_pushButton")
        self.horizontalLayout.addWidget(self.quit_popup_quit_pushButton)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.verticalLayout.addWidget(self.quit_popup_main_frame)

        self.retranslateUi(Dialog)
        self.quit_popup_cancel_pushButton.clicked.connect(Dialog.reject)
        self.quit_popup_quit_pushButton.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Warning"))
        self.quit_popup_lock_label.setText(_translate("Dialog", "4 locked assets"))
        self.quit_popup_unlock_all_pushButton.setText(_translate("Dialog", "Unlock all"))
        self.quit_popup_run_label.setText(_translate("Dialog", "2 running assets"))
        self.quit_popup_cancel_pushButton.setText(_translate("Dialog", "Cancel"))
        self.quit_popup_quit_pushButton.setText(_translate("Dialog", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
