# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\ui_files\room_button.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(389, 40)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.room_button_frame = QtWidgets.QFrame(Form)
        self.room_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.room_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.room_button_frame.setObjectName("room_button_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.room_button_frame)
        self.horizontalLayout_2.setContentsMargins(4, 2, 4, 2)
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.room_button_image_label = QtWidgets.QLabel(self.room_button_frame)
        self.room_button_image_label.setMinimumSize(QtCore.QSize(32, 32))
        self.room_button_image_label.setMaximumSize(QtCore.QSize(32, 32))
        self.room_button_image_label.setText("")
        self.room_button_image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.room_button_image_label.setObjectName("room_button_image_label")
        self.horizontalLayout_2.addWidget(self.room_button_image_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.room_button_name_label = QtWidgets.QLabel(self.room_button_frame)
        self.room_button_name_label.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.room_button_name_label.setObjectName("room_button_name_label")
        self.verticalLayout.addWidget(self.room_button_name_label)
        self.room_button_last_message_label = QtWidgets.QLabel(self.room_button_frame)
        self.room_button_last_message_label.setStyleSheet("color:gray;")
        self.room_button_last_message_label.setText("")
        self.room_button_last_message_label.setObjectName("room_button_last_message_label")
        self.verticalLayout.addWidget(self.room_button_last_message_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.room_button_count_label = QtWidgets.QLabel(self.room_button_frame)
        self.room_button_count_label.setMinimumSize(QtCore.QSize(16, 16))
        self.room_button_count_label.setMaximumSize(QtCore.QSize(26, 16))
        self.room_button_count_label.setAlignment(QtCore.Qt.AlignCenter)
        self.room_button_count_label.setObjectName("room_button_count_label")
        self.horizontalLayout_2.addWidget(self.room_button_count_label)
        self.horizontalLayout.addWidget(self.room_button_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.room_button_name_label.setText(_translate("Form", "name"))
        self.room_button_count_label.setText(_translate("Form", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
