# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\softwares_prefs_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(622, 460)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.setup_softwares_comboBox = QtWidgets.QComboBox(self.frame_2)
        self.setup_softwares_comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.setup_softwares_comboBox.setObjectName("setup_softwares_comboBox")
        self.horizontalLayout.addWidget(self.setup_softwares_comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setVerticalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.executable_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.executable_lineEdit.setReadOnly(False)
        self.executable_lineEdit.setObjectName("executable_lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.executable_lineEdit)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.env_textEdit = QtWidgets.QTextEdit(self.frame)
        self.env_textEdit.setObjectName("env_textEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.env_textEdit)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.additionnal_textEdit = QtWidgets.QTextEdit(self.frame)
        self.additionnal_textEdit.setObjectName("additionnal_textEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.additionnal_textEdit)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.command_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.command_lineEdit.setObjectName("command_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.command_lineEdit)
        self.verticalLayout_2.addWidget(self.frame)
        self.save_setup_pushButton = QtWidgets.QPushButton(Dialog)
        self.save_setup_pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.save_setup_pushButton.setObjectName("save_setup_pushButton")
        self.verticalLayout_2.addWidget(self.save_setup_pushButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.log_frame = QtWidgets.QFrame(Dialog)
        self.log_frame.setObjectName("log_frame")
        self.log_layout = QtWidgets.QHBoxLayout(self.log_frame)
        self.log_layout.setContentsMargins(0, 0, 0, 0)
        self.log_layout.setSpacing(0)
        self.log_layout.setObjectName("log_layout")
        self.log_lineEdit = QtWidgets.QLineEdit(self.log_frame)
        self.log_lineEdit.setReadOnly(True)
        self.log_lineEdit.setObjectName("log_lineEdit")
        self.log_layout.addWidget(self.log_lineEdit)
        self.verticalLayout.addWidget(self.log_frame)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Software"))
        self.label_2.setText(_translate("Dialog", "Executable"))
        self.executable_lineEdit.setPlaceholderText(_translate("Dialog", "path/to/software/software.exe..."))
        self.label_3.setText(_translate("Dialog", "Environment variables"))
        self.env_textEdit.setPlaceholderText(_translate("Dialog", "PYTHONPATH = path/to/python..."))
        self.label_4.setText(_translate("Dialog", "Additionnal scripts folders"))
        self.additionnal_textEdit.setPlaceholderText(_translate("Dialog", "path/to/myscripts/..."))
        self.label_5.setText(_translate("Dialog", "Command"))
        self.command_lineEdit.setPlaceholderText(_translate("Dialog", "\"[executable]\" \"[file]\""))
        self.save_setup_pushButton.setText(_translate("Dialog", "  Save software setup"))
        self.log_lineEdit.setPlaceholderText(_translate("Dialog", "Warnings and logs here..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
