# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\wizard_devellop\App\gui\ui_files\subprocess_manager.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1011, 847)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.subprocess_details_frame = QtWidgets.QFrame(Form)
        self.subprocess_details_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.subprocess_details_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.subprocess_details_frame.setObjectName("subprocess_details_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subprocess_details_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.subprocess_details_frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.subprocess_command_textEdit = QtWidgets.QTextEdit(self.subprocess_details_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subprocess_command_textEdit.sizePolicy().hasHeightForWidth())
        self.subprocess_command_textEdit.setSizePolicy(sizePolicy)
        self.subprocess_command_textEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.subprocess_command_textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.subprocess_command_textEdit.setObjectName("subprocess_command_textEdit")
        self.verticalLayout_2.addWidget(self.subprocess_command_textEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.subprocess_execute_pushButton = QtWidgets.QPushButton(self.subprocess_details_frame)
        self.subprocess_execute_pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.subprocess_execute_pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.subprocess_execute_pushButton.setObjectName("subprocess_execute_pushButton")
        self.horizontalLayout_2.addWidget(self.subprocess_execute_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.subprocess_details_frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.process_stdout_textEdit = QtWidgets.QTextEdit(self.subprocess_details_frame)
        self.process_stdout_textEdit.setMinimumSize(QtCore.QSize(0, 360))
        self.process_stdout_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.process_stdout_textEdit.setObjectName("process_stdout_textEdit")
        self.verticalLayout_3.addWidget(self.process_stdout_textEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.subprocess_details_frame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.process_stderr_textEdit = QtWidgets.QTextEdit(self.subprocess_details_frame)
        self.process_stderr_textEdit.setObjectName("process_stderr_textEdit")
        self.verticalLayout_4.addWidget(self.process_stderr_textEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.save_logs_pushButton = QtWidgets.QPushButton(self.subprocess_details_frame)
        self.save_logs_pushButton.setMinimumSize(QtCore.QSize(210, 40))
        self.save_logs_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.save_logs_pushButton.setObjectName("save_logs_pushButton")
        self.horizontalLayout_9.addWidget(self.save_logs_pushButton)
        self.copy_logs_pushButton = QtWidgets.QPushButton(self.subprocess_details_frame)
        self.copy_logs_pushButton.setMinimumSize(QtCore.QSize(210, 40))
        self.copy_logs_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.copy_logs_pushButton.setObjectName("copy_logs_pushButton")
        self.horizontalLayout_9.addWidget(self.copy_logs_pushButton)
        self.report_logs_pushButton = QtWidgets.QPushButton(self.subprocess_details_frame)
        self.report_logs_pushButton.setMinimumSize(QtCore.QSize(210, 40))
        self.report_logs_pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.report_logs_pushButton.setObjectName("report_logs_pushButton")
        self.horizontalLayout_9.addWidget(self.report_logs_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addWidget(self.subprocess_details_frame)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.subprocess_current_task_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.subprocess_current_task_lineEdit.setReadOnly(True)
        self.subprocess_current_task_lineEdit.setObjectName("subprocess_current_task_lineEdit")
        self.horizontalLayout_5.addWidget(self.subprocess_current_task_lineEdit)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.subprocess_status_lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.subprocess_status_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.subprocess_status_lineEdit.setReadOnly(True)
        self.subprocess_status_lineEdit.setObjectName("subprocess_status_lineEdit")
        self.horizontalLayout_6.addWidget(self.subprocess_status_lineEdit)
        self.horizontalLayout_8.addWidget(self.frame_4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.subprocess_percent_progressBar = QtWidgets.QProgressBar(self.frame_5)
        self.subprocess_percent_progressBar.setProperty("value", 0)
        self.subprocess_percent_progressBar.setObjectName("subprocess_percent_progressBar")
        self.horizontalLayout_7.addWidget(self.subprocess_percent_progressBar)
        self.horizontalLayout_11.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setMinimumSize(QtCore.QSize(46, 46))
        self.frame_6.setMaximumSize(QtCore.QSize(46, 46))
        self.frame_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.subprocess_manager_loading_label = QtWidgets.QLabel(self.frame_6)
        self.subprocess_manager_loading_label.setText("")
        self.subprocess_manager_loading_label.setAlignment(QtCore.Qt.AlignCenter)
        self.subprocess_manager_loading_label.setObjectName("subprocess_manager_loading_label")
        self.verticalLayout_5.addWidget(self.subprocess_manager_loading_label)
        self.horizontalLayout_11.addWidget(self.frame_6)
        self.subprocess_ma_stop_pushButton = QtWidgets.QPushButton(Form)
        self.subprocess_ma_stop_pushButton.setMinimumSize(QtCore.QSize(46, 46))
        self.subprocess_ma_stop_pushButton.setMaximumSize(QtCore.QSize(46, 46))
        self.subprocess_ma_stop_pushButton.setText("")
        self.subprocess_ma_stop_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.subprocess_ma_stop_pushButton.setObjectName("subprocess_ma_stop_pushButton")
        self.horizontalLayout_11.addWidget(self.subprocess_ma_stop_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.subprocess_time_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subprocess_time_lineEdit.sizePolicy().hasHeightForWidth())
        self.subprocess_time_lineEdit.setSizePolicy(sizePolicy)
        self.subprocess_time_lineEdit.setReadOnly(True)
        self.subprocess_time_lineEdit.setObjectName("subprocess_time_lineEdit")
        self.horizontalLayout_4.addWidget(self.subprocess_time_lineEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Subprocess manager"))
        self.label_2.setText(_translate("Form", "Command :"))
        self.subprocess_execute_pushButton.setText(_translate("Form", "Execute"))
        self.label_3.setText(_translate("Form", "Stdout :"))
        self.label_8.setText(_translate("Form", "Stderr :"))
        self.save_logs_pushButton.setText(_translate("Form", "Save logs ( file )"))
        self.copy_logs_pushButton.setText(_translate("Form", "Copy logs to clipboard"))
        self.report_logs_pushButton.setText(_translate("Form", "Report logs ( email )"))
        self.label_5.setText(_translate("Form", "Current task :"))
        self.label_6.setText(_translate("Form", "Status :"))
        self.label_4.setText(_translate("Form", "Progress :"))
        self.label_7.setText(_translate("Form", "Time :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
