# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\ticket_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(514, 140)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ticket_header_frame = QtWidgets.QFrame(Form)
        self.ticket_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticket_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticket_header_frame.setObjectName("ticket_header_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ticket_header_frame)
        self.horizontalLayout_4.setContentsMargins(8, 4, 4, 4)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ticket_icon_label = QtWidgets.QLabel(self.ticket_header_frame)
        self.ticket_icon_label.setMinimumSize(QtCore.QSize(24, 24))
        self.ticket_icon_label.setMaximumSize(QtCore.QSize(24, 24))
        self.ticket_icon_label.setText("")
        self.ticket_icon_label.setObjectName("ticket_icon_label")
        self.horizontalLayout_4.addWidget(self.ticket_icon_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ticket_user_label = QtWidgets.QLabel(self.ticket_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticket_user_label.sizePolicy().hasHeightForWidth())
        self.ticket_user_label.setSizePolicy(sizePolicy)
        self.ticket_user_label.setObjectName("ticket_user_label")
        self.horizontalLayout_2.addWidget(self.ticket_user_label)
        self.label = QtWidgets.QLabel(self.ticket_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ticket_adress_label = QtWidgets.QLabel(self.ticket_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticket_adress_label.sizePolicy().hasHeightForWidth())
        self.ticket_adress_label.setSizePolicy(sizePolicy)
        self.ticket_adress_label.setObjectName("ticket_adress_label")
        self.horizontalLayout_2.addWidget(self.ticket_adress_label)
        self.tiret_label = QtWidgets.QLabel(self.ticket_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tiret_label.sizePolicy().hasHeightForWidth())
        self.tiret_label.setSizePolicy(sizePolicy)
        self.tiret_label.setObjectName("tiret_label")
        self.horizontalLayout_2.addWidget(self.tiret_label)
        self.ticket_date_label = QtWidgets.QLabel(self.ticket_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticket_date_label.sizePolicy().hasHeightForWidth())
        self.ticket_date_label.setSizePolicy(sizePolicy)
        self.ticket_date_label.setObjectName("ticket_date_label")
        self.horizontalLayout_2.addWidget(self.ticket_date_label)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addWidget(self.ticket_header_frame)
        self.delete_ticket_pushButton = QtWidgets.QPushButton(Form)
        self.delete_ticket_pushButton.setMinimumSize(QtCore.QSize(34, 34))
        self.delete_ticket_pushButton.setMaximumSize(QtCore.QSize(34, 34))
        self.delete_ticket_pushButton.setText("")
        self.delete_ticket_pushButton.setObjectName("delete_ticket_pushButton")
        self.horizontalLayout_5.addWidget(self.delete_ticket_pushButton)
        self.change_ticket_state_pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.change_ticket_state_pushButton.sizePolicy().hasHeightForWidth())
        self.change_ticket_state_pushButton.setSizePolicy(sizePolicy)
        self.change_ticket_state_pushButton.setMinimumSize(QtCore.QSize(0, 34))
        self.change_ticket_state_pushButton.setMaximumSize(QtCore.QSize(110, 16777215))
        self.change_ticket_state_pushButton.setObjectName("change_ticket_state_pushButton")
        self.horizontalLayout_5.addWidget(self.change_ticket_state_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.ticket_main_frame = QtWidgets.QFrame(Form)
        self.ticket_main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ticket_main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ticket_main_frame.setObjectName("ticket_main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ticket_main_frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ticket_message_label = QtWidgets.QLabel(self.ticket_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticket_message_label.sizePolicy().hasHeightForWidth())
        self.ticket_message_label.setSizePolicy(sizePolicy)
        self.ticket_message_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ticket_message_label.setWordWrap(True)
        self.ticket_message_label.setObjectName("ticket_message_label")
        self.verticalLayout.addWidget(self.ticket_message_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line = QtWidgets.QFrame(self.ticket_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(30, 0))
        self.line.setMaximumSize(QtCore.QSize(30, 16777215))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.ticket_comment_label = QtWidgets.QLabel(self.ticket_main_frame)
        self.ticket_comment_label.setWordWrap(True)
        self.ticket_comment_label.setObjectName("ticket_comment_label")
        self.horizontalLayout_6.addWidget(self.ticket_comment_label)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ticket_state_label = QtWidgets.QLabel(self.ticket_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticket_state_label.sizePolicy().hasHeightForWidth())
        self.ticket_state_label.setSizePolicy(sizePolicy)
        self.ticket_state_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ticket_state_label.setObjectName("ticket_state_label")
        self.horizontalLayout_3.addWidget(self.ticket_state_label)
        self.ticket_close_user_label = QtWidgets.QLabel(self.ticket_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticket_close_user_label.sizePolicy().hasHeightForWidth())
        self.ticket_close_user_label.setSizePolicy(sizePolicy)
        self.ticket_close_user_label.setText("")
        self.ticket_close_user_label.setObjectName("ticket_close_user_label")
        self.horizontalLayout_3.addWidget(self.ticket_close_user_label)
        self.close_date_label = QtWidgets.QLabel(self.ticket_main_frame)
        self.close_date_label.setText("")
        self.close_date_label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.close_date_label.setObjectName("close_date_label")
        self.horizontalLayout_3.addWidget(self.close_date_label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.ticket_main_frame)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ticket_user_label.setText(_translate("Form", "user label"))
        self.label.setText(_translate("Form", ">"))
        self.ticket_adress_label.setText(_translate("Form", "adress label"))
        self.tiret_label.setText(_translate("Form", "-"))
        self.ticket_date_label.setText(_translate("Form", "date_label"))
        self.change_ticket_state_pushButton.setText(_translate("Form", "Close ticket"))
        self.ticket_message_label.setText(_translate("Form", "message_label"))
        self.ticket_comment_label.setText(_translate("Form", "comment_label"))
        self.ticket_state_label.setText(_translate("Form", "state_label"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
