# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard\App\work\ui_files\wall_widget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(320, 805)
        Form.setMaximumSize(QtCore.QSize(320, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wall_widget_header_frame = QtWidgets.QFrame(Form)
        self.wall_widget_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wall_widget_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wall_widget_header_frame.setObjectName("wall_widget_header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wall_widget_header_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.notif_image_label = QtWidgets.QLabel(self.wall_widget_header_frame)
        self.notif_image_label.setMinimumSize(QtCore.QSize(40, 40))
        self.notif_image_label.setMaximumSize(QtCore.QSize(40, 40))
        self.notif_image_label.setText("")
        self.notif_image_label.setObjectName("notif_image_label")
        self.horizontalLayout.addWidget(self.notif_image_label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wall_environment_label = QtWidgets.QLabel(self.wall_widget_header_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wall_environment_label.sizePolicy().hasHeightForWidth())
        self.wall_environment_label.setSizePolicy(sizePolicy)
        self.wall_environment_label.setObjectName("wall_environment_label")
        self.horizontalLayout_2.addWidget(self.wall_environment_label)
        self.wall_environment_label_2 = QtWidgets.QLabel(self.wall_widget_header_frame)
        self.wall_environment_label_2.setText("")
        self.wall_environment_label_2.setObjectName("wall_environment_label_2")
        self.horizontalLayout_2.addWidget(self.wall_environment_label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.creation_filter_pushButton = QtWidgets.QPushButton(self.wall_widget_header_frame)
        self.creation_filter_pushButton.setMinimumSize(QtCore.QSize(60, 0))
        self.creation_filter_pushButton.setCheckable(True)
        self.creation_filter_pushButton.setChecked(True)
        self.creation_filter_pushButton.setObjectName("creation_filter_pushButton")
        self.horizontalLayout_3.addWidget(self.creation_filter_pushButton)
        self.publish_filter_pushButton = QtWidgets.QPushButton(self.wall_widget_header_frame)
        self.publish_filter_pushButton.setMinimumSize(QtCore.QSize(60, 0))
        self.publish_filter_pushButton.setCheckable(True)
        self.publish_filter_pushButton.setChecked(True)
        self.publish_filter_pushButton.setObjectName("publish_filter_pushButton")
        self.horizontalLayout_3.addWidget(self.publish_filter_pushButton)
        self.remove_filter_pushButton = QtWidgets.QPushButton(self.wall_widget_header_frame)
        self.remove_filter_pushButton.setMinimumSize(QtCore.QSize(60, 0))
        self.remove_filter_pushButton.setCheckable(True)
        self.remove_filter_pushButton.setChecked(True)
        self.remove_filter_pushButton.setObjectName("remove_filter_pushButton")
        self.horizontalLayout_3.addWidget(self.remove_filter_pushButton)
        self.new_filter_pushButton = QtWidgets.QPushButton(self.wall_widget_header_frame)
        self.new_filter_pushButton.setMinimumSize(QtCore.QSize(50, 0))
        self.new_filter_pushButton.setCheckable(True)
        self.new_filter_pushButton.setObjectName("new_filter_pushButton")
        self.horizontalLayout_3.addWidget(self.new_filter_pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.wall_widget_header_frame)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wall_scrollArea = QtWidgets.QScrollArea(self.frame)
        self.wall_scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.wall_scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wall_scrollArea.setWidgetResizable(True)
        self.wall_scrollArea.setObjectName("wall_scrollArea")
        self.wall_scrollArea_widget = QtWidgets.QWidget()
        self.wall_scrollArea_widget.setGeometry(QtCore.QRect(0, 0, 316, 720))
        self.wall_scrollArea_widget.setObjectName("wall_scrollArea_widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.wall_scrollArea_widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.wall_scrollArea.setWidget(self.wall_scrollArea_widget)
        self.verticalLayout_2.addWidget(self.wall_scrollArea)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.wall_environment_label.setText(_translate("Form", "Concern :"))
        self.creation_filter_pushButton.setText(_translate("Form", "Creation"))
        self.publish_filter_pushButton.setText(_translate("Form", "Publish"))
        self.remove_filter_pushButton.setText(_translate("Form", "Remove"))
        self.new_filter_pushButton.setText(_translate("Form", "New"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
