# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\conta\Documents\script\Wizard_clean\App\gui\ui_files\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(792, 403)
        Dialog.setMinimumSize(QtCore.QSize(792, 403))
        Dialog.setMaximumSize(QtCore.QSize(792, 403))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.welcome_main_frame = QtWidgets.QFrame(Dialog)
        self.welcome_main_frame.setMinimumSize(QtCore.QSize(0, 381))
        self.welcome_main_frame.setMaximumSize(QtCore.QSize(16777215, 381))
        self.welcome_main_frame.setObjectName("welcome_main_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.welcome_main_frame)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.welcome_image_label = QtWidgets.QLabel(self.welcome_main_frame)
        self.welcome_image_label.setMinimumSize(QtCore.QSize(200, 381))
        self.welcome_image_label.setMaximumSize(QtCore.QSize(200, 381))
        self.welcome_image_label.setText("")
        self.welcome_image_label.setObjectName("welcome_image_label")
        self.horizontalLayout.addWidget(self.welcome_image_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(15, 8, 15, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.welcome_main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.welcome_wizard_logo_label = QtWidgets.QLabel(self.frame)
        self.welcome_wizard_logo_label.setMinimumSize(QtCore.QSize(50, 50))
        self.welcome_wizard_logo_label.setMaximumSize(QtCore.QSize(50, 50))
        self.welcome_wizard_logo_label.setText("")
        self.welcome_wizard_logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_wizard_logo_label.setObjectName("welcome_wizard_logo_label")
        self.horizontalLayout_2.addWidget(self.welcome_wizard_logo_label)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.close_pushButton = QtWidgets.QPushButton(self.frame)
        self.close_pushButton.setMinimumSize(QtCore.QSize(26, 26))
        self.close_pushButton.setMaximumSize(QtCore.QSize(26, 26))
        self.close_pushButton.setText("")
        self.close_pushButton.setIconSize(QtCore.QSize(11, 11))
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_2.addWidget(self.close_pushButton)
        self.verticalLayout.addWidget(self.frame)
        self.welcome_stacked_widget_frame = QtWidgets.QFrame(self.welcome_main_frame)
        self.welcome_stacked_widget_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.welcome_stacked_widget_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.welcome_stacked_widget_frame.setObjectName("welcome_stacked_widget_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.welcome_stacked_widget_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.welcome_left_pushButton = QtWidgets.QPushButton(self.welcome_stacked_widget_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_left_pushButton.sizePolicy().hasHeightForWidth())
        self.welcome_left_pushButton.setSizePolicy(sizePolicy)
        self.welcome_left_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.welcome_left_pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.welcome_left_pushButton.setText("")
        self.welcome_left_pushButton.setObjectName("welcome_left_pushButton")
        self.horizontalLayout_3.addWidget(self.welcome_left_pushButton)
        self.welcome_main_widget_layout = QtWidgets.QHBoxLayout()
        self.welcome_main_widget_layout.setObjectName("welcome_main_widget_layout")
        self.horizontalLayout_3.addLayout(self.welcome_main_widget_layout)
        self.welcome_right_pushButton = QtWidgets.QPushButton(self.welcome_stacked_widget_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_right_pushButton.sizePolicy().hasHeightForWidth())
        self.welcome_right_pushButton.setSizePolicy(sizePolicy)
        self.welcome_right_pushButton.setMinimumSize(QtCore.QSize(30, 0))
        self.welcome_right_pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.welcome_right_pushButton.setText("")
        self.welcome_right_pushButton.setObjectName("welcome_right_pushButton")
        self.horizontalLayout_3.addWidget(self.welcome_right_pushButton)
        self.verticalLayout.addWidget(self.welcome_stacked_widget_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.welcome_version_label = QtWidgets.QLabel(self.welcome_main_frame)
        self.welcome_version_label.setObjectName("welcome_version_label")
        self.horizontalLayout_7.addWidget(self.welcome_version_label)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.welcome_main_frame)

        self.retranslateUi(Dialog)
        self.close_pushButton.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome to Wizard Pipeline Manager !"))
        self.welcome_version_label.setText(_translate("Dialog", "Beta 0.9.1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
